import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {syntheticFailureDiagnostics} from './browser-diagnostics.mjs';
async function fixture(report,log){const output=await mkdtemp(join(tmpdir(),'kplasma-diagnostics-'));await mkdir(join(output,'browser'));if(report)await writeFile(join(output,'browser/results.json'),JSON.stringify(report));if(log)await writeFile(join(output,'browser.log'),log);return output;}
const failed={title:'P-structure-02 memory boundaries',file:'core-flows.spec.ts',line:67,column:3,tests:[{status:'unexpected',results:[{status:'failed',errors:[{message:'\u001b[31mError: expect(received).toBe(expected)\u001b[0m\nExpected: 2\nReceived: 4\npassword=private-secret Bearer private-bearer\nhttp://127.0.0.1:8888/api/runs?token=secret\n{"password":"private-json-secret"}\n\n  67 | source code NOT_FOR_STDOUT'}],attachments:[{body:'PRIVATE_ATTACHMENT_SENTINEL'}],stdout:[{text:'PRIVATE_STDOUT_SENTINEL'}]}]}]};
test('synthetic JSON failure includes case location and safe bounded assertion summary',async()=>{const output=await fixture({suites:[{suites:[{specs:[failed]}]}]});try{const lines=await syntheticFailureDiagnostics(output,{mode:'artificial-only'});const text=lines.join('\n');assert.match(text,/P-structure-02 memory boundaries/);assert.match(text,/core-flows.spec.ts:67:3/);assert.match(text,/Expected: 2/);assert.match(text,/Received: 4/);assert.doesNotMatch(text,/private-secret|private-bearer|private-json-secret|token=secret|PRIVATE_.*SENTINEL|NOT_FOR_STDOUT|\u001b/);assert.ok(text.length<=4096);}finally{await rm(output,{recursive:true,force:true});}});
test('external reference mode never emits report or private log content',async()=>{const output=await fixture({suites:[{specs:[failed]}]},'Error: REAL_DATA_SENTINEL');try{assert.deepEqual(await syntheticFailureDiagnostics(output,{mode:'external-reference'}),[]);assert.deepEqual(await syntheticFailureDiagnostics('/missing-reference-report',{mode:'external-reference'}),[]);}finally{await rm(output,{recursive:true,force:true});}});
test('missing JSON uses only bounded error header from private synthetic browser log',async()=>{const output=await fixture(null,'environment dump NOT_FOR_STDOUT\nError: Timed out waiting 60000ms from config.webServer.\npassword=private-secret\nstack and attachment NOT_FOR_STDOUT');try{const text=(await syntheticFailureDiagnostics(output,{mode:'artificial-only'})).join('\n');assert.match(text,/config.webServer/);assert.doesNotMatch(text,/NOT_FOR_STDOUT|private-secret/);}finally{await rm(output,{recursive:true,force:true});}});
test('caps failure count and total output while ignoring successful cases',async()=>{const cases=Array.from({length:30},(_,i)=>({...failed,title:`failure${i} ${'x'.repeat(2000)}`,tests:[{status:'unexpected',results:[{status:'failed',errors:[{message:'Error: '+ 'synthetic assertion '.repeat(1000)}]}]}]}));cases.unshift({title:'SUCCESS_NOT_FOR_STDOUT',tests:[{status:'expected',results:[]}]});const output=await fixture({suites:[{specs:cases}]});try{const lines=await syntheticFailureDiagnostics(output,{mode:'artificial-only'});assert.ok(lines.length<=6);assert.ok(lines.join('\n').length<=4096);assert.doesNotMatch(lines.join('\n'),/SUCCESS_NOT_FOR_STDOUT/);assert.match(lines.join('\n'),/failure0/);}finally{await rm(output,{recursive:true,force:true});}});
test('report-level startup error is diagnosed when no browser cases were collected',async()=>{const output=await fixture({suites:[],errors:[{message:'Error: browserType.launch: Executable missing'}]});try{assert.match((await syntheticFailureDiagnostics(output,{mode:'artificial-only'})).join('\n'),/Executable missing/);}finally{await rm(output,{recursive:true,force:true});}});
