import {expect,test} from '@playwright/test';
import {toRunSummary,type AgentRequestView,type TurnSnapshot,type WorkspaceView} from 'agent';
import {syntheticRun} from '../../test/runs';
import {emptyWorkspace,initialTurnUi} from './useConversation';
const a=syntheticRun();const b=syntheticRun(800);const ref=(run:typeof a)=>({runId:run.runId,runVersionId:run.runVersionId});
const comparison={kind:'compare_runs',resultStatus:'COMPARISON_PARTIAL',baseline:ref(a),target:ref(b),conditions:[{field:'biasPower',baseline:600,target:800,delta:200,unit:'W',status:'AVAILABLE'}],metrics:[{metric:'ionFlux',baseline:0,target:3,delta:3,percentChange:null,unit:'10¹⁸ m⁻²s⁻¹',status:'PERCENT_UNAVAILABLE',reason:'ZERO_BASELINE'}],changedConditions:['biasPower']};
const explanation={kind:'explain_concept',resultStatus:'CONCEPT_READY',knowledgeBasis:'MODEL_GENERAL_KNOWLEDGE',explanation:{status:'answered',sections:[{topic_refs:['ionFlux'],text:'단위 면적을 통과하는 이온의 유량을 뜻합니다.'}],limitations:['일반 지식에 기반한 설명입니다.']},limitations:[]};
const objective={id:'objective-1',metric:'ionFlux',operator:'MIN',comparisonOperator:'gte',value:2,unit:'10¹⁸ m⁻²s⁻¹'};
const evaluated=[a,b].map(run=>({run:toRunSummary(run),evaluations:[{objectiveId:objective.id,metric:'ionFlux',actual:run.metrics.ionFlux,satisfied:true,targetLabel:'≥ 2',boundaryDelta:0}]}));
const snapshots=[{kind:'forward_lookup',resultStatus:'EXACT',candidates:[toRunSummary(a)],selectedRun:toRunSummary(a)},{kind:'reverse_search',resultStatus:'MATCH',objectives:[objective],commonCandidates:evaluated,objectiveResults:[{objective,candidates:evaluated,allConstraintsGuaranteed:false}],goalResults:[],nearMisses:[]},comparison,{kind:'explain_change',resultStatus:'CHANGE_READY',comparison,knowledgeBasis:'MODEL_GENERAL_KNOWLEDGE',causality:'NOT_ESTABLISHED',explanation:{status:'answered',interpretations:[{text:'다른 조건의 변화도 함께 살펴볼 필요가 있습니다.',observation_refs:['ionFlux'],assumptions:[]}],limitations:['관찰만으로 원인을 확정할 수 없습니다.'],suggested_checks:[]},limitations:[]},explanation];
const intents=['FORWARD_LOOKUP','REVERSE_SEARCH','RUN_COMPARISON','CHANGE_EXPLANATION','CONCEPT_EXPLANATION'] as const;
for(const width of [390,800,1008,1440])test(`v1 five cards, pending clarification, reload and detail at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 const turns=snapshots.map((result,index)=>({id:`t${index}`,askedAt:'2026-10-05T00:00:00Z',question:`인공 시나리오 ${index+1}`,intent:intents[index],context:null,answerRunRefs:index===4?[]:[ref(a),ref(b)],answerSnapshot:JSON.parse(JSON.stringify({implementationId:'v1',schemaVersion:1,kind:result.kind,summary:'검증용 인공 응답',result})),ui:structuredClone(initialTurnUi)} satisfies TurnSnapshot));
 let pending:AgentRequestView={requestId:'pending-1',requestRevision:2,status:'NEEDS_INPUT',stage:'decide',graphVersion:'v1',question:'이온 플럭스에 대해 설명해줘',pendingInput:{id:'input-1',message:'어떤 개념을 설명할까요?'},error:null,partialResult:null,turnId:null,answerSnapshot:null,inputEvents:[]};
 let workspace:WorkspaceView={...structuredClone(emptyWorkspace),conversation:{version:1,activeRun:null,turns},activeAgentRequest:pending};let resumes=0;let submissions=0;
 let holdTabSaves=true;const tabSaves:(()=>void)[]=[];
 await page.route('**/api/**',async route=>{const req=route.request();const path=new URL(req.url()).pathname;if(!path.startsWith('/api/'))return route.continue();const body=req.postDataJSON();if(path==='/api/decisions')return route.fulfill({json:[]});if(path==='/api/runs')return route.fulfill({json:[a,b].map(toRunSummary)});if(path.startsWith('/api/run-versions/'))return route.fulfill({json:path.endsWith(a.runVersionId)?a:b});if(path.endsWith('/resume')){resumes++;expect(body).toEqual({expectedRequestRevision:2,pendingInputId:'input-1',input:{text:'이온 플럭스'}});pending={...pending,status:'COMPLETED',turnId:'t5',pendingInput:null};workspace={...workspace,activeAgentRequest:null,conversation:{...workspace.conversation,turns:[...workspace.conversation.turns,{...turns[4],id:'t5',question:'이온 플럭스에 대해 설명해줘'}]}};return route.fulfill({json:pending});}if(path==='/api/agent/requests'){submissions++;return route.fulfill({json:pending});}if(path.endsWith('/ui')){if(holdTabSaves)await new Promise<void>(resolve=>tabSaves.push(resolve));expect(body.stateToken).toEqual(workspace.stateToken);const turn=workspace.conversation.turns.find(turn=>path.includes(turn.id))!;turn.ui={...turn.ui,...body.ui};workspace={...workspace,stateToken:{...workspace.stateToken,revision:workspace.stateToken.revision+1}};}return route.fulfill({json:workspace});});
 await page.goto('/');await expect(page.locator('[data-implementation="v1"]')).toHaveCount(5);await expect(page.getByText('추가 정보가 필요합니다')).toBeVisible();await expect(page.getByText('LLM 일반 지식 기반')).toHaveCount(2);
 const reverse=page.locator('[data-turn-id="t1"]');
 await reverse.getByRole('tab',{name:'Ion Flux 조건 2'}).click();
 await expect(reverse.getByRole('tab',{name:'Ion Flux 조건 2'})).toHaveAttribute('aria-selected','true');
 await expect.poll(()=>tabSaves.length).toBe(1);
 expect(workspace.conversation.turns[1].ui.activeCandidateGroup).toBe('common');
 await reverse.getByRole('tab',{name:'조건 일치 결과 2'}).click();
 await expect(reverse.getByRole('tab',{name:'조건 일치 결과 2'})).toHaveAttribute('aria-selected','true');
 tabSaves[0]();await expect.poll(()=>tabSaves.length).toBe(2);
 await expect(reverse.getByRole('tab',{name:'조건 일치 결과 2'})).toHaveAttribute('aria-selected','true');
 tabSaves[1]();await expect.poll(()=>workspace.stateToken.revision).toBe(2);holdTabSaves=false;
 await reverse.getByRole('tab',{name:'Ion Flux 조건 2'}).click();
 await expect.poll(()=>workspace.conversation.turns[1].ui.activeCandidateGroup).toBe('objective-0');
 await expect(reverse.getByText('개별 조건의 후보입니다. 모든 필수 조건을 만족하는 공통 후보와 구분합니다.')).toBeVisible();
 await expect(reverse.locator('.agent-fit-card')).toHaveCount(2);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await reverse.getByRole('button',{name:'실험 기록하기'}).click();
 const record=page.getByRole('dialog');await expect(record).toBeVisible();
 expect(await record.evaluate(node=>node.scrollWidth<=node.clientWidth+1)).toBe(true);
 await record.getByRole('radio',{name:`${b.runId} 채택`}).check();
 await record.getByRole('button',{name:'다음: 후보별 판단'}).click();
 await expect(record.getByText('2. 후보별 판단 기록')).toBeVisible();
 expect(await record.evaluate(node=>node.scrollWidth<=node.clientWidth+1)).toBe(true);
 await page.keyboard.press('Escape');await expect(record).toBeHidden();
 await page.locator('[data-turn-id="t2"]').getByRole('button',{name:'실험 상세'}).first().click();await expect(page.getByRole('dialog')).toBeVisible();expect(await page.getByRole('dialog').evaluate(node=>node.scrollWidth<=node.clientWidth+1)).toBe(true);await page.keyboard.press('Escape');
 await page.getByRole('textbox',{name:'어떤 개념을 설명할까요?'}).fill('이온 플럭스');await page.getByRole('button',{name:'답변하고 계속'}).click();await expect(page.locator('.agent-turn')).toHaveCount(6);await page.reload();await expect(page.locator('.agent-turn')).toHaveCount(6);await expect(reverse.getByRole('tab',{name:'Ion Flux 조건 2'})).toHaveAttribute('aria-selected','true');await expect(reverse.getByText('개별 조건의 후보입니다. 모든 필수 조건을 만족하는 공통 후보와 구분합니다.')).toBeVisible();expect(submissions).toBe(0);expect(resumes).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:info.outputPath(`synthetic-v1-${width}.png`),fullPage:true});
});
