import {fireEvent,render,screen} from '@testing-library/react';
import {expect,test,vi} from 'vitest';
import {createRecord,executeFallback,toRunSummary,type ReviewRecord,type TurnSnapshot} from 'agent';
import {fixtureRuns} from '../../test/runs';
import {AgentPage,candidateRefs} from './AgentPage';
import {AnswerView} from './AnswerView';
import {emptyWorkspace,initialTurnUi,type ConversationController} from './useConversation';
async function candidateTurn(){const response=await executeFallback({text:'Ion Flux는 높게, Mean Ion Energy는 30–40 eV에 가깝게 후보를 찾아줘',candidateReferences:[]},{candidateRunsLatest:fixtureRuns.map(toRunSummary),referenceRunsByVersion:new Map(),decisionRecords:[],hydrateFullRun:async ref=>fixtureRuns.find(r=>r.runId===ref.runId)!});return {id:'t1',askedAt:'2026-01-01T00:00:00Z',question:'후보 찾아줘',intent:response.intent,context:null,answerRunRefs:response.usedRunRefs,answerSnapshot:response.answerSnapshot,ui:initialTurnUi} satisfies TurnSnapshot;}
test('candidate card keyboard selects only its turn; group reference selects the whole active group without submitting',async()=>{const turn=await candidateTurn();const submit=vi.fn(async()=>{});const updateTurnUi=vi.fn(async()=>{});const setReference=vi.fn<ConversationController['setReference']>(async()=>{});render(<AgentPage conversation={{state:{...emptyWorkspace,conversation:{...emptyWorkspace.conversation,turns:[turn]}},ready:true,error:'',pending:false,activeRequest:null,sending:false,resume:async()=>{},cancel:async()=>{},submit,updateTurnUi,setReference,refresh:async()=>{},newConversation:async()=>{},reset:async()=>{}}} records={[]} notify={()=>{}} onDetail={()=>{}} onRecord={()=>{}} onEvidence={()=>{}} onDemo={async()=>{}}/>);const cards=document.querySelectorAll('.agent-fit-card-selectable');fireEvent.keyDown(cards[0],{key:' '});expect(updateTurnUi).toHaveBeenCalledWith('t1',{selectedCandidateRunId:cards[0].getAttribute('data-run-id')});expect(setReference).not.toHaveBeenCalled();expect(submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'전체 후보 채팅에 추가'}));const update=setReference.mock.calls[0][0];expect(typeof update==='function'?update(emptyWorkspace):update).toEqual({kind:'후보 집합',runs:candidateRefs(turn)});expect(submit).not.toHaveBeenCalled();});
test('examples and quick followups execute immediately, while Enter stays a textarea newline',()=>{const submit=vi.fn(async()=>{});render(<AgentPage conversation={{state:{...emptyWorkspace,conversation:{...emptyWorkspace.conversation,activeRun:fixtureRuns[0]}},ready:true,error:'',pending:false,activeRequest:null,sending:false,resume:async()=>{},cancel:async()=>{},submit,updateTurnUi:async()=>{},setReference:async()=>{},refresh:async()=>{},newConversation:async()=>{},reset:async()=>{}}} records={[]} notify={()=>{}} onDetail={()=>{}} onRecord={()=>{}} onEvidence={()=>{}} onDemo={async()=>{}}/>);fireEvent.keyDown(screen.getByRole('textbox',{name:'공정 데이터에 질문하기'}),{key:'Enter'});expect(submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Energy만 조금 높게'}));expect(submit).toHaveBeenCalledWith('이 결과에서 이온 에너지만 조금 더 높은 실제 조건 찾아줘',undefined);fireEvent.click(screen.getByRole('button',{name:/Run 조건 조회/}));expect(submit).toHaveBeenCalledWith('압력 8 mTorr, 소스 300 W, 바이어스 600 W 결과를 보여줘',undefined);});
test('answer adapter preserves escaped text and removes legacy event attributes',()=>{const turn={id:'safe',askedAt:'',question:'',intent:'CLARIFICATION',context:null,answerRunRefs:[],answerSnapshot:{intent:'CLARIFICATION',summary:'<img src=x onerror="alert(1)">',missingConditions:['pressure']},ui:initialTurnUi} satisfies TurnSnapshot;render(<AnswerView turn={turn} onAction={()=>{}}/>);expect(screen.getByText('<img src=x onerror="alert(1)">')).toBeInTheDocument();expect(document.querySelector('script,img,[onerror],[onclick]')).toBeNull();});

test('candidate role resolves latest A independently of historical baseline A',async()=>{const latest=fixtureRuns[0];const historical={...latest,runVersionId:'historical-A',metrics:{...latest.metrics,meanIonEnergy:20}};const response=await executeFallback({text:'Mean Ion Energy 30–40 eV인 실제 Run 후보를 모두 찾아줘',baseline:historical,candidateReferences:[]},{candidateRunsLatest:[toRunSummary(latest)],referenceRunsByVersion:new Map([[historical.runVersionId,historical]]),decisionRecords:[],hydrateFullRun:async()=>latest});const turn:TurnSnapshot={id:'versions',askedAt:'',question:'후보',intent:response.intent,context:historical,answerRunRefs:response.usedRunRefs,answerSnapshot:response.answerSnapshot,ui:initialTurnUi};expect(turn.answerRunRefs.map(ref=>ref.runVersionId)).toEqual(['historical-A',latest.runVersionId]);expect(candidateRefs(turn)).toEqual([{runId:latest.runId,runVersionId:latest.runVersionId}]);});


test('numeric excluded row details use latest result version while threshold and undo retain old retry reference',async()=>{
 const latest=fixtureRuns[0];const historical={...latest,runVersionId:'historical-excluded'};const other=fixtureRuns[1];const raw=createRecord({targetRunId:latest.runId,decision:'REJECT',comment:'비용이 높아 예산 초과',analysisType:'FORWARD'},[historical,other]);const rejection:ReviewRecord={...raw,decision:'REJECT',targetRunRef:{runId:historical.runId,runVersionId:historical.runVersionId},comparedRunRefs:[],runSnapshots:raw.runSnapshots.map(snapshot=>({...snapshot,runVersionId:historical.runVersionId}))};const response=await executeFallback({text:'Ion Flux 1 이상인 후보를 찾되 비용 때문에 반려된 건 제외해줘',candidateReferences:[historical],clarification:{threshold:1}},{candidateRunsLatest:[latest,other].map(toRunSummary),decisionRecords:[rejection],referenceRunsByVersion:new Map([[historical.runVersionId,historical]]),hydrateFullRun:async ref=>[historical,latest,other].find(r=>r.runVersionId===ref.runVersionId)!});const turn:TurnSnapshot={id:'excluded',askedAt:'',question:'',intent:response.intent,context:null,answerRunRefs:response.usedRunRefs,answerSnapshot:response.answerSnapshot,ui:initialTurnUi};const {resolveCandidateRef,displayAnswer}=await import('./references');expect(displayAnswer(response.answerSnapshot).memoryResult?.excluded.map(r=>r.runId)).toContain(latest.runId);expect(resolveCandidateRef(turn,latest.runId)).toEqual({runId:latest.runId,runVersionId:latest.runVersionId});expect(displayAnswer(response.answerSnapshot).memoryRequest?.referenceRunRefs).toEqual([{runId:latest.runId,runVersionId:historical.runVersionId}]);
});
