/* eslint-disable @typescript-eslint/no-explicit-any -- Synthetic HTTP request fixture models endpoint-specific bodies. */
import {act,renderHook,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,test,vi} from 'vitest';
import type {WorkspaceView} from 'agent';
import {toRunSummary} from 'agent';
import {syntheticRun} from '../../test/runs';
import {useConversation,emptyWorkspace} from './useConversation';
let workspace:WorkspaceView;let requests:{path:string;body:any}[];
const a=syntheticRun();const b={...syntheticRun(800),metrics:{ionFlux:3,meanIonEnergy:46,iedWidth:8}};const c={...syntheticRun(1000),metrics:{ionFlux:4,meanIonEnergy:90,iedWidth:8}};
beforeEach(()=>{workspace=structuredClone(emptyWorkspace);requests=[];vi.stubGlobal('fetch',vi.fn(async(path:string,init:RequestInit={})=>{const body=init.body?JSON.parse(init.body as string):null;requests.push({path,body});if(path==='/api/runs')return Response.json([a,b,c].map(toRunSummary));if(path.startsWith('/api/run-versions/'))return Response.json([a,b,c].find(r=>path.endsWith(r.runVersionId)));if(path==='/api/decisions')return Response.json([]);if(path.endsWith('/reference')){workspace={...workspace,candidateReference:body.candidateReference,conversation:{...workspace.conversation,activeRun:body.activeRun}};}else if(path.endsWith('/turns'))workspace.conversation.turns.push(body.turn);else if(path.endsWith('/ui')){const t=workspace.conversation.turns.find(t=>path.includes(t.id))!;t.ui={...t.ui,...body.ui,runDetailTabs:{...t.ui.runDetailTabs,...body.ui.runDetailTabs}};}else if(path.endsWith('/reset')||path.endsWith('/new-conversation')){workspace={...workspace,candidateReference:null,conversation:{version:1,activeRun:null,turns:[]}};}if(init.method)workspace.stateToken={...workspace.stateToken,revision:workspace.stateToken.revision+1};return Response.json(workspace);}));});
afterEach(()=>vi.unstubAllGlobals());
test('reference-only actions independently persist active Run and all candidate refs without a question',async()=>{const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));await act(()=>result.current.setReference({kind:'후보 집합',runs:[a,b]},a));expect(result.current.state.conversation.activeRun?.runId).toBe(a.runId);expect(result.current.state.candidateReference?.runs).toHaveLength(2);expect(result.current.state.conversation.turns).toHaveLength(0);expect(requests.some(r=>r.path==='/api/runs')).toBe(false);});
test('Energy followup keeps mandatory baseline +5–20 eV range and persists every used version',async()=>{const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));await act(()=>result.current.setReference(null,a));await act(()=>result.current.submit('이 결과에서 이온 에너지만 조금 더 높은 실제 조건 찾아줘'));const turn=result.current.state.conversation.turns[0];expect(turn.answerSnapshot.constraints).toContainEqual(expect.objectContaining({metric:'meanIonEnergy',operator:'RANGE',min:41,max:56}));expect(turn.answerRunRefs.map(r=>r.runVersionId)).toContain(a.runVersionId);expect(turn.answerRunRefs.map(r=>r.runVersionId)).toContain(b.runVersionId);expect(turn.answerRunRefs.map(r=>r.runVersionId)).not.toContain(c.runVersionId);await act(()=>result.current.updateTurnUi(turn.id,{selectedCandidateRunId:b.runId,runDetailTabs:{[b.runId]:'ied'}}));expect(result.current.state.conversation.turns[0].ui.selectedCandidateRunId).toBe(b.runId);expect(result.current.state.conversation.activeRun?.runId).toBe(a.runId);});
test('reset discards an old fallback response even if transport ignores abort',async()=>{let resolve!:(value:Response)=>void;const original=globalThis.fetch;vi.stubGlobal('fetch',vi.fn((path:string,init?:RequestInit)=>path==='/api/runs'?new Promise<Response>(r=>resolve=r):original(path,init)));const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));let old!:Promise<void>;act(()=>{old=result.current.submit('평균 이온 에너지가 뭐야?');});await waitFor(()=>expect(resolve).toBeDefined());await act(()=>result.current.reset());await act(async()=>{resolve(Response.json([a,b].map(toRunSummary)));await old;});expect(result.current.state.candidateReference).toEqual(null);expect(result.current.state.conversation.activeRun).toEqual(null);expect(result.current.state.conversation.turns).toEqual([]);expect(requests.filter(r=>r.path.endsWith('/turns'))).toHaveLength(0);});

test('persisted turn selection and detail tabs restore on reload without rerunning fallback',async()=>{const first=renderHook(()=>useConversation());await waitFor(()=>expect(first.result.current.ready).toBe(true));await act(()=>first.result.current.submit('평균 이온 에너지가 뭐야?'));const id=first.result.current.state.conversation.turns[0].id;await act(()=>first.result.current.updateTurnUi(id,{selectedCandidateRunId:a.runId,runDetailTabs:{[a.runId]:'potential'},activeCandidateGroup:'energy'}));first.unmount();requests=[];const next=renderHook(()=>useConversation());await waitFor(()=>expect(next.result.current.ready).toBe(true));expect(next.result.current.state.conversation.turns[0].ui).toMatchObject({selectedCandidateRunId:a.runId,activeCandidateGroup:'energy',runDetailTabs:{[a.runId]:'potential'}});expect(requests.map(r=>r.path)).toEqual(['/api/workspace']);});
test('pending record reuse persists historical reference versions even when candidate list is empty',async()=>{const historical={...a,runVersionId:'historical-a'};const original=globalThis.fetch;vi.stubGlobal('fetch',vi.fn((path:string,init?:RequestInit)=>path.endsWith('historical-a')?Promise.resolve(Response.json(historical)):original(path,init)));const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));await act(()=>result.current.setReference({kind:'후보 집합',runs:[historical,b]}));await act(()=>result.current.submit('이 후보들 중 비용 때문에 많이 반려된 건 제외해줘.'));const turn=result.current.state.conversation.turns[0];expect(turn.answerSnapshot.pendingThreshold).toBe(true);expect(turn.answerRunRefs).toEqual([{runId:a.runId,runVersionId:'historical-a'},{runId:b.runId,runVersionId:b.runVersionId}]);});
