import {expect,test,type Page} from '@playwright/test';
import {fixtureRuns} from '../../test/runs';
import {toRunSummary,type DecisionRecord} from 'agent';
import {emptyWorkspace} from './useConversation';
const prototype=process.env.KPLASMA_PROTOTYPE_URL;
async function setup(page:Page,original=false){
 page.on('pageerror',error=>console.error('PAGE ERROR',error.message));page.on('console',message=>{if(message.type()==='error')console.error('BROWSER CONSOLE',message.text());});
 let workspace=structuredClone(emptyWorkspace);let records:DecisionRecord[]=[];
 await page.route('**/api/**',async route=>{const req=route.request();const path=new URL(req.url()).pathname;if(!path.startsWith('/api/')){await route.continue();return;}const body=req.postDataJSON();if(path==='/api/runs'){await route.fulfill({json:fixtureRuns.map(toRunSummary)});return;}if(path.startsWith('/api/run-versions/')){await route.fulfill({json:fixtureRuns.find(run=>path.endsWith(run.runVersionId))});return;}if(path==='/api/decisions'){if(req.method()==='POST')records.push(body.record);await route.fulfill({json:req.method()==='POST'?body.record:records});return;}if(path.endsWith('/turns'))workspace.conversation.turns.push(body.turn);else if(path.endsWith('/ui')){const turn=workspace.conversation.turns.find(turn=>path.includes(turn.id))!;turn.ui={...turn.ui,...body.ui,runDetailTabs:{...turn.ui.runDetailTabs,...body.ui.runDetailTabs}};}else if(path.endsWith('/reference'))workspace={...workspace,candidateReference:body.candidateReference,conversation:{...workspace.conversation,activeRun:body.activeRun}};else if(path.endsWith('/reset')||path.endsWith('/new-conversation')){workspace={...workspace,candidateReference:null,conversation:{version:1,activeRun:null,turns:[]}};if(path.endsWith('/reset')){records=[];workspace.stateToken.workspaceEpoch++;}workspace.stateToken.conversationEpoch++;}if(req.method()!=='GET')workspace.stateToken.revision++;await route.fulfill({json:workspace});});
 if(original)await page.route('**/assets/analysis-data.js',route=>route.fulfill({contentType:'text/javascript',body:`window.KPlasmaAnalysisData=${JSON.stringify({meta:{actualRunCount:150},runs:fixtureRuns})};`}));
 await page.goto(original?prototype!:'/');await expect(page.locator('.agent-welcome')).toBeVisible();
}
async function navigate(page:Page,view:string){if(page.viewportSize()!.width<760)await page.getByRole('button',{name:'메뉴 열기'}).click();await page.locator(`.nav-stack [data-view="${view}"]`).click();}
async function compare(page:Page,original:Page,selectors:string[]){for(const selector of selectors){const actual=await page.locator(selector).first().boundingBox();const expected=await original.locator(selector).first().boundingBox();for(const key of ['x','y','width','height'] as const)expect(actual![key],`${selector} ${key}`).toBeCloseTo(expected![key],0);}}
for(const width of [390,800,1008,1440])test(`Agent/EXP/archive parity with synthetic APIs at ${width}px`,async({page,context},info)=>{
 test.skip(!prototype,'Set untouched local prototype URL; all Run payloads are synthetic route fixtures.');await page.setViewportSize({width,height:1000});await setup(page);const original=await context.newPage();await original.setViewportSize({width,height:1000});await setup(original,true);
 await compare(page,original,['.agent-page-header','.agent-welcome','.agent-composer','.agent-examples']);
 for(const p of [page,original]){await p.locator('#agent-query').fill('Ion Flux는 높게, Mean Ion Energy는 30–40 eV에 가깝게 후보를 찾아줘');await p.locator('#agent-query-form [type="submit"]').click();await expect(p.locator('.agent-fit-card').first()).toBeVisible();}
 expect(await page.locator('.agent-response').textContent()).toEqual(await original.locator('.agent-response').textContent());await compare(page,original,['.agent-response','.agent-fit-grid','.agent-fit-card']);
 await page.screenshot({path:info.outputPath(`react-agent-${width}.png`),fullPage:true});await original.screenshot({path:info.outputPath(`original-agent-${width}.png`),fullPage:true});
 const runId=await page.locator('.agent-fit-card-selectable').first().getAttribute('data-run-id');
 for(const p of [page,original]){await p.getByRole('button',{name:'실험 자세히 보기',exact:true}).first().click();await expect(p.locator('.agent-detail-graph svg')).toBeVisible();}
 await compare(page,original,['.run-detail-modal','.agent-run-detail']);
 for(const tab of ['ied','iad','iead','current','potential','density','residual']){for(const p of [page,original])await p.locator(`.agent-detail-tabs [data-tab="${tab}"]`).click();const graph=async(p:Page)=>p.locator('.agent-detail-graph svg').evaluate(svg=>{function tree(node:Element):unknown{return {tag:node.tagName,attrs:Object.fromEntries([...node.attributes].map(a=>[a.name,a.value]).sort()),text:node.children.length?null:node.textContent,children:[...node.children].map(tree)};}return tree(svg);});expect(await graph(page)).toEqual(await graph(original));}
 await page.screenshot({path:info.outputPath(`react-turn-detail-${width}.png`),fullPage:true});await original.screenshot({path:info.outputPath(`original-turn-detail-${width}.png`),fullPage:true});for(const p of [page,original])await p.keyboard.press('Escape');
for(const p of [page,original]){await p.locator('.agent-fit-card-selectable').first().focus();await p.keyboard.press('Space');await expect(p.locator('.agent-fit-card.is-selected')).toHaveCount(1);await p.getByRole('button',{name:'전체 후보 기준 질문'}).click();await expect(p.locator('.agent-composer .reference-tray')).toBeVisible();await p.getByRole('button',{name:'실험 기록하기',exact:true}).click();await expect(p.getByRole('dialog')).toBeVisible();await p.getByLabel(`${runId} 채택`,{exact:true}).check();await p.getByRole('button',{name:'다음: 후보별 판단'}).click();await expect(p.getByRole('dialog')).toBeFocused();await p.getByRole('textbox',{name:'후보별 판단 메모 선택'}).fill('<img onerror=alert(1)> 메모');await p.getByRole('textbox',{name:'공통 실험 코멘트 필수'}).fill('저장 당시 판단');await p.getByRole('button',{name:'이전: 후보 구성'}).click();await p.getByRole('button',{name:'표',exact:true}).click();await p.getByRole('button',{name:'다음: 후보별 판단'}).click();await expect(p.getByRole('dialog')).toBeFocused();await expect(p.getByRole('textbox',{name:'후보별 판단 메모 선택'})).toHaveValue('<img onerror=alert(1)> 메모');}
 await compare(page,original,['.experiment-record-modal','.record-judgement-card']);await page.screenshot({path:info.outputPath(`react-exp-${width}.png`),fullPage:true});await original.screenshot({path:info.outputPath(`original-exp-${width}.png`),fullPage:true});
 for(const p of [page,original]){await p.getByRole('button',{name:'실험 기록 저장',exact:true}).click();await expect(p.getByRole('dialog')).toHaveCount(0);await navigate(p,'archive');await p.locator('.archive-row').click();await expect(p.getByText('<img onerror=alert(1)> 메모')).toBeVisible();expect(await p.locator('img,[onerror]').count()).toBe(0);}
 await compare(page,original,['.archive-detail-modal','.run-snapshot-grid']);await page.screenshot({path:info.outputPath(`react-archive-${width}.png`),fullPage:true});await original.screenshot({path:info.outputPath(`original-archive-${width}.png`),fullPage:true});await page.keyboard.press('Escape');await original.keyboard.press('Escape');await page.getByRole('textbox',{name:'작성자'}).fill(' 익명 ');await page.getByRole('button',{name:'필터 적용'}).click();await navigate(page,'agent');await page.reload();await expect(page.locator('.agent-fit-card.is-selected')).toHaveCount(1);await expect(page.locator('.agent-composer .reference-tray')).toBeVisible();await navigate(page,'archive');await expect(page.locator('.archive-row')).toHaveCount(1);
 await original.close();
});
