/* eslint-disable @typescript-eslint/no-explicit-any -- Heterogeneous synthetic HTTP endpoint bodies. */
/* Synthetic endpoint fixtures exercise browser persistence; numeric computation lives in Python tests. */
import {act,renderHook,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,test,vi} from 'vitest';
import type {AgentRequestView,TurnSnapshot,WorkspaceView} from 'agent';
import {syntheticRun} from '../../test/runs';
import {useConversation,emptyWorkspace,initialTurnUi} from './useConversation';
let workspace:WorkspaceView;let requests:{path:string;body:any}[];let id=0;
const a=syntheticRun();const b=syntheticRun(800);const asRef=(r:typeof a)=>({runId:r.runId,runVersionId:r.runVersionId});
const requestView=(status:AgentRequestView['status']='COMPLETED'):AgentRequestView=>({requestId:`request-${id}`,requestRevision:0,status,stage:'commit',graphVersion:'v1',question:'질문',pendingInput:null,error:null,partialResult:null,turnId:`turn-${id}`,answerSnapshot:null,inputEvents:[]});
beforeEach(()=>{workspace=structuredClone(emptyWorkspace);requests=[];id=0;vi.stubGlobal('fetch',vi.fn(async(path:string,init:RequestInit={})=>{const body=init.body?JSON.parse(init.body as string):null;requests.push({path,body});if(path==='/api/agent/requests'){id++;const turn:TurnSnapshot={id:`turn-${id}`,askedAt:'2026-10-05T00:00:00Z',question:body.text,intent:'CONCEPT_EXPLANATION',context:workspace.conversation.activeRun,answerRunRefs:[],answerSnapshot:{implementationId:'v1',schemaVersion:1,kind:'explain_concept',summary:'서버가 저장한 설명',result:{kind:'explain_concept',resultStatus:'CONCEPT_READY',explanation:{sections:[{text:'일반 지식 설명',topic_refs:['meanIonEnergy']}]}}},ui:structuredClone(initialTurnUi)};workspace={...workspace,conversation:{...workspace.conversation,turns:[...workspace.conversation.turns,turn]},activeAgentRequest:null};return Response.json(requestView());}if(path.startsWith('/api/agent/requests/'))return Response.json(workspace.activeAgentRequest??requestView());if(path.endsWith('/reference')){workspace={...workspace,activeAgentRequest:null,candidateReference:body.candidateReference,conversation:{...workspace.conversation,activeRun:body.activeRun}};}else if(path.endsWith('/ui')){const t=workspace.conversation.turns.find(t=>path.includes(t.id))!;t.ui={...t.ui,...body.ui,runDetailTabs:{...t.ui.runDetailTabs,...body.ui.runDetailTabs}};}else if(path.endsWith('/reset')||path.endsWith('/new-conversation')){workspace={...workspace,activeAgentRequest:null,failedAgentRequest:null,candidateReference:null,conversation:{version:1,activeRun:null,turns:[]}};}if(init.method)workspace.stateToken={...workspace.stateToken,revision:workspace.stateToken.revision+1};return Response.json(workspace);}));});
afterEach(()=>vi.unstubAllGlobals());
test('reference-only actions persist active Run and all candidates without executing a question',async()=>{const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));await act(()=>result.current.setReference({kind:'후보 집합',runs:[a,b]},a));expect(result.current.state.conversation.activeRun?.runId).toBe(a.runId);expect(result.current.state.candidateReference?.runs).toHaveLength(2);expect(result.current.state.conversation.turns).toHaveLength(0);expect(requests.some(r=>r.path==='/api/agent/requests')).toBe(false);});
test.each(['reset','newConversation','reference'] as const)('%s discards an old accepted response even when transport ignores abort',async action=>{let resolve!:(value:Response)=>void;const original=globalThis.fetch;vi.stubGlobal('fetch',vi.fn((path:string,init?:RequestInit)=>path==='/api/agent/requests'?new Promise<Response>(r=>resolve=r):original(path,init)));const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));let old!:Promise<void>;act(()=>{old=result.current.submit('평균 이온 에너지가 뭐야?');});await waitFor(()=>expect(resolve).toBeDefined());await act(()=>action==='reference'?result.current.setReference(null,b):result.current[action]());await act(async()=>{resolve(Response.json(requestView('RUNNING')));await old;});expect(result.current.state.conversation.activeRun).toEqual(action==='reference'?asRef(b):null);expect(result.current.state.conversation.turns).toEqual([]);expect(result.current.activeRequest).toBeNull();expect(requests.filter(r=>r.path.endsWith('/turns'))).toHaveLength(0);});
test('persisted selection and detail tabs restore on reload without executing a model',async()=>{const first=renderHook(()=>useConversation());await waitFor(()=>expect(first.result.current.ready).toBe(true));await act(()=>first.result.current.submit('평균 이온 에너지가 뭐야?'));const turn=first.result.current.state.conversation.turns[0];await act(()=>first.result.current.updateTurnUi(turn.id,{selectedCandidateRunId:a.runId,runDetailTabs:{[a.runId]:'potential'},activeCandidateGroup:'energy'}));first.unmount();requests=[];const next=renderHook(()=>useConversation());await waitFor(()=>expect(next.result.current.ready).toBe(true));expect(next.result.current.state.conversation.turns[0].ui).toMatchObject({selectedCandidateRunId:a.runId,activeCandidateGroup:'energy',runDetailTabs:{[a.runId]:'potential'}});expect(next.result.current.state.conversation.turns[0].answerSnapshot).toEqual(turn.answerSnapshot);expect(requests.map(r=>r.path)).toEqual(['/api/workspace']);});
test.each([false,true])('early reference waits for authoritative initialization (write fails: %s)',async fail=>{let resolve!:(response:Response)=>void;const original=globalThis.fetch;const loaded={...structuredClone(emptyWorkspace),stateToken:{workspaceEpoch:3,conversationEpoch:2,revision:7}};let first=true;vi.stubGlobal('fetch',vi.fn((path:string,init?:RequestInit)=>{if(path==='/api/workspace'&&first){first=false;return new Promise<Response>(r=>resolve=r);}if(path.endsWith('/reference')&&fail)return Promise.resolve(Response.json({message:'reference failed'},{status:500}));return original(path,init);}));const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(resolve).toBeDefined());let mutation!:Promise<void>;act(()=>{mutation=result.current.setReference(null,a);});const outcome=mutation.catch(()=>{});await act(async()=>{workspace=loaded;resolve(Response.json(loaded));await outcome;});expect(result.current.ready).toBe(true);expect(result.current.state.stateToken.workspaceEpoch).toBe(3);expect(result.current.state.conversation.activeRun).toEqual(fail?null:asRef(a));await act(()=>result.current.submit('평균 이온 에너지가 뭐야?'));expect(result.current.state.conversation.turns).toHaveLength(1);});
test.each([{selectedCandidateRunId:'A'},{activeCandidateGroup:'energy'},{runDetailTabs:{A:'ied'}}])('past turn UI revision preserves active server request: %j',async patch=>{const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));await act(()=>result.current.submit('평균 이온 에너지가 뭐야?'));const past=result.current.state.conversation.turns[0].id;workspace.activeAgentRequest=requestView('RUNNING');await act(()=>result.current.refresh());await act(()=>result.current.updateTurnUi(past,patch));expect(result.current.pending).toBe(true);expect(result.current.activeRequest?.requestId).toBe(workspace.activeAgentRequest.requestId);expect(result.current.state.conversation.turns[0].ui).toMatchObject(patch);expect(requests.some(r=>r.path.endsWith('/cancel'))).toBe(false);});
test('transport failure retries the same idempotency key and payload',async()=>{const original=globalThis.fetch;const attempts:{body:string;key:string|null}[]=[];let first=true;vi.stubGlobal('fetch',vi.fn((path:string,init:RequestInit={})=>{if(path==='/api/agent/requests'){attempts.push({body:String(init.body),key:new Headers(init.headers).get('Idempotency-Key')});if(first){first=false;return Promise.reject(new TypeError('Network disconnected'));}}return original(path,init);}));const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));await act(()=>result.current.submit('평균 이온 에너지가 뭐야?').catch(()=>{}));await act(()=>result.current.submit('평균 이온 에너지가 뭐야?'));expect(attempts).toHaveLength(2);expect(attempts[0]).toEqual(attempts[1]);expect(result.current.state.conversation.turns).toHaveLength(1);});
