import {ComparisonCharts} from './ComparisonCharts';
import {useRunColors} from '../../components/RunColors';
import type {ComparisonAnswer,ComparisonResultV2,ComparisonResultV3,ScalarDatum} from 'agent';
import type {ComparisonResult,ComparisonRow} from './agent-contract';
import {metricNames,numberText,reasons} from './agent-contract';
import type {AnswerAction} from './AnswerView';
const scalarText=(value:ScalarDatum)=>value.status==='AVAILABLE'?`${numberText(value.value)} ${value.unit}`:`— (${reasons[value.reason??'']??value.reason})${value.sourceValue?` · 원값 ${numberText(value.sourceValue.value)} ${value.sourceValue.unit}`:''}`;
function MultiRunComparison({result,answer,onAction,storageId}:{storageId?:string;result:ComparisonResultV2;answer?:ComparisonAnswer|null;onAction?:AnswerAction}){
 const colors=useRunColors(result.runs.map(r=>r.ref.runId));
 const extended='outputs' in result?result as ComparisonResultV3:undefined;
 const directional=result.comparisons.some(row=>row.kind!=='absolute_difference');
 const observations=result.observations.filter(o=>answer?.observationIds.includes(o.id));
 return <section className="v1-comparison"><h3>선택한 실험 비교 · {result.runs.length}개</h3><p>{result.baselineKey?`${result.baselineKey} 기준 · 변화량 = 대상 − 기준`:result.mode==='trend'?'다른 조건이 같은 집합에서 축 순서에 따른 변화량을 비교합니다.':'기준 미지정 · 값과 절대 차이·범위를 비교합니다.'}</p><div className="comparison-layout"><div className="comparison-numbers"><div className="v1-table-scroll" tabIndex={0}><table className="v1-comparison-table"><thead><tr><th>실험</th>{result.metricIds.map(metric=><th key={metric}>{metricNames[metric]}<small>{result.runs[0]?.metrics[metric]?.unit}</small></th>)}</tr></thead><tbody>{result.runs.map(run=><tr key={run.key}><th><i className="comparison-color" style={{background:colors.get(run.ref.runId)}}/>{run.key} · {run.ref.runId}<details className="v1-run-metadata"><summary>공정 조건·버전</summary><small>{(['pressure','sourcePower','biasPower'] as const).map(key=>scalarText(run.conditions[key])).join(' · ')}</small><small>버전 {run.ref.runVersionId}</small><small>{Object.values(run.quality).join(' · ')}</small></details>{onAction&&<button className="button button--ghost button--small" type="button" data-run-id={run.ref.runId} data-run-version-id={run.ref.runVersionId} onClick={e=>onAction('open-run-detail',e.currentTarget)}>실험 상세</button>}</th>{result.metricIds.map(metric=><td key={metric}>{run.metrics[metric]?.status==='AVAILABLE'?numberText(run.metrics[metric]!.value):scalarText(run.metrics[metric]!)}</td>)}</tr>)}</tbody></table></div>
 {result.comparisons.length>0&&<><h4>계산된 차이</h4><div className="v1-table-scroll" tabIndex={0}><table className="v1-comparison-table"><thead><tr><th>실험</th><th>지표</th><th>{directional?'변화량':'절대 차이'}</th>{directional&&<th>변화율</th>}</tr></thead><tbody>{result.comparisons.map(row=><tr key={row.id}><th>{row.leftKey} {row.kind==='absolute_difference'?'↔':'→'} {row.rightKey}</th><td>{metricNames[row.metric]}</td><td>{scalarText(row.difference)}</td>{directional&&<td>{row.percentChange?scalarText(row.percentChange):'—'}</td>}</tr>)}</tbody></table></div></>}
 {result.mode==='overview'&&<><h4>선택한 실험의 범위</h4><div className="v1-table-scroll" tabIndex={0}><table className="v1-comparison-table"><thead><tr><th>지표</th><th>최솟값</th><th>최댓값</th><th>범위 폭</th><th>가용 실험</th></tr></thead><tbody>{result.summaries.map(row=><tr key={row.id}><th>{metricNames[row.metric]}</th><td>{scalarText(row.minimum)}</td><td>{scalarText(row.maximum)}</td><td>{scalarText(row.range)}</td><td>{row.availableCount}개</td></tr>)}</tbody></table></div></>}
 {result.trends.length>0&&<><h4>같은 조건 집합의 경향</h4><ul>{result.observations.filter(o=>o.source.kind==='trend').map(o=><li key={o.id}>{o.text}</li>)}</ul></>}
 {extended&&<details className="comparison-source-info"><summary>계산 정의·원본</summary><p>피크 = 최대 y값 · 첨두간 값 = 최댓값 − 최솟값 · 반첨두간 진폭 = 첨두간 값 / 2. IED 폭은 저장된 P90−P10입니다.</p><ul>{extended.outputs.map(o=><li key={`${o.ref.runVersionId}:${o.outputId}`}>{o.ref.runId} · {o.outputId} · {o.status==='AVAILABLE'?`원본 ${o.sourceCount}점 · ${o.valueUnit}`:`비가용: ${o.reason}`}<small>버전 {o.ref.runVersionId} · 원본 {o.sourceIntegrity??'확인 불가'}</small>{o.extrema.maximum&&<small>공동 최대 {o.extrema.maximum.count}개 · 첫 위치 {numberText(o.extrema.maximum.x)} {o.xUnit}{o.extrema.maximum.y!=null?` / ${numberText(o.extrema.maximum.y)} ${o.yUnit}`:''}</small>}</li>)}</ul></details>}
 </div><ComparisonCharts result={result} storageId={storageId}/></div>
 {observations.length>0&&<details className="v1-calculation-evidence"><summary>계산 근거</summary><ul>{observations.map(o=><li key={o.id}>{o.text}</li>)}</ul></details>}
 {answer&&<>{answer.interpretations.length>0&&<><h4>가능한 해석</h4>{answer.interpretations.map((item,index)=><div key={index}><p>{item.text}</p>{item.assumptions.length>0&&<ul>{item.assumptions.map((text,i)=><li key={i}>{text}</li>)}</ul>}</div>)}</>}{answer.limitations.length>0&&<><h4>설명의 한계</h4><ul>{answer.limitations.map((text,i)=><li key={i}>{text}</li>)}</ul></>}</>}
 {result.resultStatus==='NO_COMPARABLE_DATA'&&<p className="alert">비교 가능한 측정값이 부족합니다.</p>}{result.resultStatus==='COMPARISON_PARTIAL'&&<p className="alert">일부 값이나 변화율은 계산할 수 없습니다. 표의 비가용 이유를 확인해 주세요.</p>}</section>;
}
export function RunComparisonCard({result,answer,onAction,storageId}:{storageId?:string;result:ComparisonResult|ComparisonResultV2;answer?:ComparisonAnswer|null;onAction?:AnswerAction}){
 if('runs' in result)return <MultiRunComparison result={result} answer={answer} onAction={onAction} storageId={storageId}/>;
 function table(rows:ComparisonRow[],percent:boolean){return <div className="v1-table-scroll" tabIndex={0}><table className="v1-comparison-table"><thead><tr><th>항목</th><th>기준</th><th>대상</th><th>차이</th>{percent&&<th>변화율</th>}<th>단위·비가용 이유</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${row.metric??row.field}-${index}`}><th>{metricNames[row.metric??row.field??'']??row.metric??row.field}</th><td>{numberText(row.baseline)}</td><td>{numberText(row.target)}</td><td>{numberText(row.delta,2,true)}</td>{percent&&<td>{row.percentChange==null?'—':`${numberText(row.percentChange,1,true)}%`}</td>}<td>{row.unit}<small>{row.reason?(reasons[row.reason]??row.reason):''}</small>{row.sourceValues&&<small>원값: {row.sourceValues.baseline?`${numberText(row.sourceValues.baseline.value)} ${row.sourceValues.baseline.unit}`:'—'} → {row.sourceValues.target?`${numberText(row.sourceValues.target.value)} ${row.sourceValues.target.unit}`:'—'}</small>}</td></tr>)}</tbody></table></div>;}
 return <section className="v1-comparison"><h3>Run 수치 비교</h3><div className="v1-run-pair">{([['baseline','기준'],['target','대상']] as const).map(([role,label])=><div key={role}><small>{label}</small><strong>{result[role].runId}</strong><small>버전 {result[role].runVersionId}</small><small>{Object.values(result.quality?.[role]??{}).join(' · ')}</small>{onAction&&<button type="button" className="button button--ghost button--small" data-run-id={result[role].runId} data-run-version-id={result[role].runVersionId} onClick={e=>onAction('open-run-detail',e.currentTarget)}>실험 상세</button>}</div>)}</div><p>차이 = 대상 − 기준 · 변화율은 기준값의 크기에 대한 비율입니다.</p><h4>공정 조건</h4>{table(result.conditions??[],false)}<h4>결과 지표</h4>{table(result.metrics??[],true)}{result.resultStatus==='NO_COMPARABLE_DATA'&&<p className="alert">비교할 수 있는 결과 지표가 없습니다.</p>}{result.resultStatus==='COMPARISON_PARTIAL'&&<p className="alert">일부 항목은 비교하거나 변화율을 계산할 수 없습니다.</p>}<p className="v1-limitation">수치 차이는 관찰 결과이며 원인을 확정하지 않습니다.</p></section>;
}
