import {act,fireEvent,render,renderHook,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,test,vi} from 'vitest';
import type {DecisionRecord,ExperimentRecord,RunRef,TurnSnapshot} from 'agent';
import {syntheticRun} from '../../test/runs';
import {AgentPage} from './AgentPage';
import {DecisionDialog} from '../archive/DecisionDialog';
import {emptyWorkspace,initialTurnUi,useConversation,type ConversationController} from './useConversation';
import {resolveCandidateRef} from './references';
const latest=syntheticRun();const old={...latest,runVersionId:'historical-version',metrics:{...latest.metrics,meanIonEnergy:999}};
const ref=(run:RunRef)=>({runId:run.runId,runVersionId:run.runVersionId});
const turn:TurnSnapshot={id:'versioned-turn',askedAt:'',question:'후보 찾기',intent:'REVERSE_SEARCH',context:ref(old),answerRunRefs:[ref(latest),ref(old)],answerSnapshot:JSON.parse(JSON.stringify({implementationId:'v1',schemaVersion:1,kind:'reverse_search',result:{kind:'reverse_search',resultStatus:'MATCH',commonCandidates:[{run:latest,evaluations:[]}],goalResults:[],nearMisses:[]}})),ui:{...initialTurnUi,selectedCandidateRunId:latest.runId}};
afterEach(()=>vi.unstubAllGlobals());
test('v1 detail and continue use the displayed version when the same Run has historical context',async()=>{const onDetail=vi.fn();const setReference=vi.fn<ConversationController['setReference']>(async()=>{});render(<AgentPage conversation={{state:{...emptyWorkspace,conversation:{version:1,activeRun:null,turns:[turn]}},ready:true,error:'',pending:false,provisionalMessage:null,activeRequest:null,sending:false,submit:async()=>{},resume:async()=>{},cancel:async()=>{},updateTurnUi:async()=>{},setReference,refresh:async()=>{},newConversation:async()=>{},reset:async()=>{}}} records={[]} notify={()=>{}} onDetail={onDetail} onRecord={()=>{}} onEvidence={()=>{}} onDemo={async()=>{}}/>);expect(document.querySelector('.agent-fit-card')).toHaveTextContent(String(latest.metrics.meanIonEnergy));fireEvent.click(screen.getByRole('button',{name:'실험 자세히 보기'}));expect(onDetail).toHaveBeenCalledWith(ref(latest),turn);fireEvent.click(screen.getByRole('button',{name:'채팅에 추가하기'}));await waitFor(()=>expect(setReference).toHaveBeenCalledTimes(1));const update=setReference.mock.calls[0][0];expect(typeof update==='function'?update(emptyWorkspace):update).toEqual({kind:'단일 Run',runs:[ref(latest)]});expect(resolveCandidateRef(turn,latest.runId)).toEqual(ref(latest));});
test('v1 manual decision hydrates and saves only the exact displayed candidate version',async()=>{const calls:string[]=[];vi.stubGlobal('fetch',vi.fn(async(path:string)=>{calls.push(path);return Response.json(path.endsWith(old.runVersionId)?old:latest);}));const save=vi.fn(async(_record:DecisionRecord,_refs:RunRef[])=>{void _record;void _refs;});render(<DecisionDialog turn={turn} workspaceEpoch={0} onSave={save} onClose={()=>{}}/>);fireEvent.click(await screen.findByLabelText(`${latest.runId} 채택`));expect(document.querySelector('.record-choice-card')).toHaveTextContent(String(latest.metrics.meanIonEnergy));fireEvent.click(screen.getByRole('button',{name:'다음: 후보별 판단'}));fireEvent.change(screen.getByRole('textbox',{name:'공통 실험 코멘트 필수'}),{target:{value:'표시된 버전 검토'}});fireEvent.click(screen.getByRole('button',{name:'실험 기록 저장'}));await waitFor(()=>expect(save).toHaveBeenCalledTimes(1));const saved=save.mock.calls[0][0] as ExperimentRecord;expect(saved.targetRunRef).toEqual(ref(latest));expect(saved.candidates[0].metrics).toEqual(latest.metrics);expect(calls).toEqual([`/api/run-versions/${latest.runVersionId}`]);});
test.each([[ref(latest),ref(old)],[ref(old),ref(latest)]])('selectedRunRef comes from the displayed candidate independently of answer ref order',async(...answerRunRefs)=>{const selectedTurn={...turn,answerRunRefs};const workspace={...emptyWorkspace,conversation:{version:1 as const,activeRun:null,turns:[selectedTurn]}};let submitted:unknown;vi.stubGlobal('fetch',vi.fn(async(path:string,init:RequestInit={})=>{if(path==='/api/agent/requests'){submitted=JSON.parse(String(init.body));return Response.json({requestId:'request',requestRevision:0,status:'FAILED',stage:'interpret',graphVersion:'v1',question:'질문',pendingInput:null,error:{code:'TEST_FAILURE',message:'실행 전 중단'},partialResult:null,turnId:null,answerSnapshot:null,inputEvents:[]});}return Response.json(workspace);}));const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));await act(()=>result.current.submit('선택한 Run을 비교해줘'));expect(submitted).toMatchObject({selectedRunRef:ref(latest)});});

test('legacy selected candidate submission preserves its existing answer reference order',async()=>{
 const legacy={...turn,answerSnapshot:{kind:'historical'},answerRunRefs:[ref(latest),ref(old)]};
 const workspace={...emptyWorkspace,conversation:{version:1 as const,activeRun:null,turns:[legacy]}};let submitted:unknown;
 vi.stubGlobal('fetch',vi.fn(async(path:string,init:RequestInit={})=>{if(path==='/api/agent/requests'){submitted=JSON.parse(String(init.body));return Response.json({requestId:'legacy-request',requestRevision:0,status:'FAILED',stage:'interpret',graphVersion:'v1',question:'질문',pendingInput:null,error:{code:'TEST_FAILURE',message:'실행 전 중단'},partialResult:null,turnId:null,answerSnapshot:null,inputEvents:[]});}return Response.json(workspace);}));
 const {result}=renderHook(()=>useConversation());await waitFor(()=>expect(result.current.ready).toBe(true));await act(()=>result.current.submit('선택한 Run을 비교해줘'));
 expect(submitted).toMatchObject({selectedRunRef:ref(latest)});
});
