import type {TurnSnapshot,RunSummary,Snapshot} from 'agent';
import type {AnswerAction} from './AnswerView';
import {ExplanationCard} from './ExplanationCard';
import {RunComparisonCard} from './RunComparisonCard';
import {metricNames,numberText,searchGroups,snapshotResult,type ComparisonResult,type ExplanationResult,type SearchResult} from './agent-contract';
const titles:Record<string,string>={forward_lookup:'조건으로 Run 조회',reverse_search:'목표에 맞는 Run 탐색',compare_runs:'기준·대상 Run 비교',explain_change:'결과 변화 설명',explain_concept:'플라즈마 개념 설명'};
function AppliedInterpretation({snapshot}:{snapshot:Snapshot}){const parsed=snapshot.interpretation as unknown as {operations?:{kind:string;inputs:Record<string,unknown>}[]}|undefined;const history=snapshot.inputHistory as unknown as {text?:string;input?:{text?:string}}[]|undefined;return <details className="v1-interpretation"><summary>질문 해석·추가 입력</summary>{(history??[]).map((event,index)=><p key={index}>{event.text??event.input?.text??''}</p>)}{parsed?.operations?.map((op,index)=><div key={index}><strong>{titles[op.kind]??op.kind}</strong><ul>{Object.entries(op.inputs).map(([key,value])=><li key={key}>{metricNames[key]??({conditions:'조회 조건',constraints:'필수 조건',goals:'탐색 목표',metrics:'비교 지표',topics:'설명 개념',aspect:'설명 범위',baseline:'기준 Run',target:'대상 Run'}[key]??key)}: {inputLabel(value)}</li>)}</ul></div>)}</details>;}
function inputLabel(value:unknown):string{if(value==null)return '미지정';if(typeof value==='string')return metricNames[value]??value;if(typeof value==='number'||typeof value==='boolean')return String(value);if(Array.isArray(value))return value.map(inputLabel).join(', ');if(typeof value==='object')return Object.entries(value).map(([key,v])=>`${metricNames[key]??key} ${inputLabel(v)}`).join(' · ');return '';}
function SearchCard({result,turn,onAction}:{result:SearchResult;turn:TurnSnapshot;onAction:AnswerAction}){const groups=searchGroups(result);const selected=groups.find(g=>g.id===turn.ui.activeCandidateGroup)??groups[0];function card(run:RunSummary){return <article key={run.runVersionId} className={`v1-run-card ${turn.ui.selectedCandidateRunId===run.runId?'is-selected':''}`}><button type="button" className="v1-run-select" aria-pressed={turn.ui.selectedCandidateRunId===run.runId} data-run-id={run.runId} data-run-version-id={run.runVersionId} onClick={e=>onAction('select-candidate-card',e.currentTarget)}><strong>{run.runId}</strong><small>버전 {run.runVersionId}</small></button><p>{numberText(run.pressure)} mTorr · Source {numberText(run.sourcePower)} W · Bias {numberText(run.biasPower)} W</p>{result.kind==='forward_lookup'&&<small>원본 파일: {typeof (run as RunSummary&{sourceFileCount?:number}).sourceFileCount==='number'?`${(run as RunSummary&{sourceFileCount:number}).sourceFileCount}개`:'개수 비가용'}</small>}<dl>{(['ionFlux','meanIonEnergy','iedWidth'] as const).map(metric=><div key={metric}><dt>{metricNames[metric]}</dt><dd>{numberText(run.metrics[metric])} {run.units[metric]}</dd></div>)}</dl><div className="v1-card-actions"><button type="button" className="button button--ghost button--small" data-run-id={run.runId} data-run-version-id={run.runVersionId} onClick={e=>onAction('open-run-detail',e.currentTarget)}>실험 상세</button><button type="button" className="button button--ghost button--small" data-run-id={run.runId} data-run-version-id={run.runVersionId} onClick={e=>onAction('continue-with-run',e.currentTarget)}>이 Run 기준 질문</button></div>{selected.id==='near'&&<ul className="v1-limitation">{result.nearMisses?.find(m=>m.run.runVersionId===run.runVersionId)?.violations.map((v,i)=><li key={i}>{metricNames[v.metric]??v.metric}: 조건 미충족{v.reason?` · ${v.reason}`:''}</li>)}</ul>}</article>;}
 return <section><h3>{titles[result.kind]}</h3>{result.resultStatus==='NEAREST_ONLY'&&<p className="v1-limitation">정확히 일치하는 Run이 없어 가장 가까운 실제 Run을 표시합니다. 요청 조건의 예측값이 아닙니다.</p>}{result.resultStatus==='NO_DATA'&&<p>조회할 수 있는 실제 Run 데이터가 없습니다.</p>}{result.kind==='reverse_search'&&<div className="v1-group-tabs" aria-label="후보 그룹">{groups.map(group=><button key={group.id} type="button" className="button button--ghost button--small" aria-pressed={selected.id===group.id} data-group-id={group.id} onClick={e=>onAction('candidate-group',e.currentTarget)}>{group.label} ({group.runs.length})</button>)}</div>}{selected.id.startsWith('objective-')&&<p className="v1-limitation">개별 조건의 후보입니다. 모든 필수 조건을 만족하는 공통 후보와 구분합니다.</p>}{selected.id.startsWith('goal-')&&<p className="v1-limitation">개별 목표의 후보입니다. 모든 필수 조건을 만족하는 공통 후보와 구분합니다.</p>}{selected.runs.length===0&&result.resultStatus!=='NO_DATA'&&<p>이 그룹에 일치하는 Run이 없습니다.</p>}<div className="v1-run-list">{selected.runs.map(card)}</div>{selected.runs.length>0&&<button className="button button--ghost button--small" type="button" onClick={e=>onAction('reference-candidate-group',e.currentTarget)}>전체 후보 기준 질문</button>}{result.kind==='reverse_search'&&groups.some(group=>group.runs.length>0)&&<button className="button button--ghost button--small" type="button" data-action="open-experiment-record" onClick={e=>onAction('open-experiment-record',e.currentTarget)}>실험 기록하기</button>}</section>;
}
function answerBody(turn:TurnSnapshot,onAction:AnswerAction){
 const snapshot=turn.answerSnapshot;
 switch(String(snapshot.kind)){
  case 'compare_runs': return <RunComparisonCard result={snapshotResult<ComparisonResult>(snapshot)} onAction={onAction}/>;
  case 'explain_change':
  case 'explain_concept': return <ExplanationCard result={snapshotResult<ExplanationResult>(snapshot)} onAction={onAction}/>;
  case 'forward_lookup':
  case 'reverse_search': return <SearchCard result={snapshotResult<SearchResult>(snapshot)} turn={turn} onAction={onAction}/>;
  default: return <p>지원 범위: 조건 조회 · 후보 탐색 · Run 비교 · 변화 설명 · 개념 설명</p>;
 }
}
export function V1AnswerView({turn,onAction}:{turn:TurnSnapshot;onAction:AnswerAction}){const snapshot=turn.answerSnapshot;return <div className="v1-answer" data-implementation="v1">{typeof snapshot.summary==='string'&&<p className="v1-summary">{snapshot.summary}</p>}{answerBody(turn,onAction)}<AppliedInterpretation snapshot={snapshot}/></div>;}
