import {createHash} from 'node:crypto';
import {expect,test,type APIRequestContext,type APIResponse,type Page} from '@playwright/test';
import {displayAnswer} from './references';
import type {DecisionRecord,DecisionWrite,RunRef,RunSummary,TurnSnapshot,WorkspaceView} from 'agent';

export interface WorkspaceDecisionGateOptions {api:string;baseURL:string;widths?:number[];candidateQuestion?:string}
interface Write {path:string;body:unknown;key:string}
interface TurnWrite {stateToken:WorkspaceView['stateToken'];turn:TurnSnapshot}
const refOf=({runId,runVersionId}:RunRef):RunRef=>({runId,runVersionId});
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function json<T>(response:APIResponse):Promise<T>{expect(response.status()).toBe(200);return response.json() as Promise<T>;}
async function workspace(request:APIRequestContext,api:string){return json<WorkspaceView>(await request.get(`${api}/api/workspace`));}
async function decisions(request:APIRequestContext,api:string){return json<DecisionRecord[]>(await request.get(`${api}/api/decisions`));}
async function navigate(page:Page,view:string){if(page.viewportSize()!.width<760)await page.getByRole('button',{name:'메뉴 열기'}).click();await page.locator(`.nav-stack [data-view="${view}"]`).click();}
function collectWrites(page:Page):Write[]{const writes:Write[]=[];page.on('request',request=>{const path=new URL(request.url()).pathname;if(path.startsWith('/api/')&&request.method()!=='GET')writes.push({path,body:request.postDataJSON(),key:request.headers()['idempotency-key']??''});});return writes;}
async function waitForTurns(page:Page,count:number){await expect(page.locator('.agent-turn')).toHaveCount(count);await expect(page.locator('#agent-query-form [type="submit"]')).toBeEnabled();}

/** Registers real HTTP/browser flows; callers must supply a dedicated, empty test workspace. No Run intake or mutation occurs. */
export function registerWorkspaceDecisionGate({api,baseURL,widths=[390,800,1008,1440],candidateQuestion='Ion Flux는 높게, Mean Ion Energy는 150–160 eV에 가깝게 후보를 찾아줘'}:WorkspaceDecisionGateOptions){
 test.describe('actual workspace and decision persistence',()=>{
  test.describe.configure({mode:'serial'});
  let runsHash='';let catalogHash='';let initialRunCount=0;
  test.beforeAll(async({request})=>{
   const initial=await workspace(request,api);expect(initial.conversation.turns).toEqual([]);expect(initial.conversation.activeRun).toBeNull();expect(initial.candidateReference).toBeNull();expect(await decisions(request,api)).toEqual([]);
   const runs=await json<RunSummary[]>(await request.get(`${api}/api/runs`));expect(runs.length).toBeGreaterThan(0);initialRunCount=runs.length;runsHash=digest(runs);catalogHash=digest(await json(await request.get(`${api}/api/catalog`)));
  });
  test.afterEach(async({request})=>{
   if(!runsHash)return;const current=await workspace(request,api);await json(await request.post(`${api}/api/workspace/reset`,{data:{stateToken:current.stateToken}}));
   expect(await decisions(request,api)).toEqual([]);expect(digest(await json(await request.get(`${api}/api/runs`)))).toBe(runsHash);expect(digest(await json(await request.get(`${api}/api/catalog`)))).toBe(catalogHash);
  });
  for(const width of widths)test(`ordinary EXP/REV, immutable turn/UI reload and lifecycle at ${width}px`,async({page,request},info)=>{
   let runSearchRequests=0;page.on('request',request=>{if(new URL(request.url()).pathname==='/api/runs')runSearchRequests++;});const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));const writes=collectWrites(page);
   await page.setViewportSize({width,height:1000});await page.goto(baseURL);await expect(page.locator('#agent-query-form [type="submit"]')).toBeEnabled();
   await page.locator('#agent-query').fill(candidateQuestion);await page.locator('#agent-query-form [type="submit"]').click();await waitForTurns(page,1);await expect(page.locator('.agent-fit-card-selectable').first()).toBeVisible();
   const first=(await workspace(request,api)).conversation.turns[0];expect(first.answerRunRefs.length).toBeGreaterThan(0);const candidateVersions=displayAnswer(first.answerSnapshot).candidateRunRefs??[];expect(candidateVersions.length).toBeGreaterThan(0);for(const candidate of candidateVersions)expect(first.answerRunRefs).toContainEqual(candidate);
   const selectedId=(await page.locator('.agent-fit-card-selectable').first().getAttribute('data-run-id'))!;const selectedRef=candidateVersions.find(ref=>ref.runId===selectedId)!;expect(selectedRef).toBeDefined();
   await page.locator('.agent-fit-card-selectable').first().focus();await page.keyboard.press('Space');await expect(page.locator('.agent-fit-card.is-selected')).toHaveCount(1);
   const detailResponse=page.waitForResponse(response=>response.url().endsWith(`/api/run-versions/${selectedRef.runVersionId}`)&&response.request().method()==='GET');await page.getByRole('button',{name:'실험 자세히 보기',exact:true}).first().click();expect((await detailResponse).status()).toBe(200);await expect(page.locator('.agent-detail-tabs')).toBeVisible();await page.locator('.agent-detail-tabs [data-tab="residual"]').click();await expect(page.locator('.agent-detail-graph svg')).toBeVisible();await page.keyboard.press('Escape');
   await page.getByRole('button',{name:'전체 후보 채팅에 추가'}).click();await expect(page.locator('.agent-composer .reference-tray')).toBeVisible();const referenced=await workspace(request,api);expect(referenced.conversation.turns).toHaveLength(1);expect(referenced.candidateReference?.runs).toContainEqual(refOf(selectedRef));
   const searchesBeforeReload=runSearchRequests;await page.reload();await waitForTurns(page,1);expect(runSearchRequests).toBe(searchesBeforeReload);await expect(page.locator('.agent-fit-card.is-selected')).toHaveCount(1);await expect(page.locator('.agent-composer .reference-tray')).toBeVisible();const restored=await workspace(request,api);expect(restored.conversation.turns[0].ui.selectedCandidateRunId).toBe(selectedId);expect(restored.conversation.turns[0].ui.runDetailTabs[selectedId]).toBe('residual');expect(restored.conversation.turns[0].answerSnapshot).toEqual(first.answerSnapshot);
   await page.getByRole('button',{name:'실험 자세히 보기',exact:true}).first().click();await expect(page.locator('.agent-detail-tabs [data-tab="residual"]')).toHaveAttribute('aria-selected','true');await page.keyboard.press('Escape');

   // Delay only delivery of the real Run request so a real UI PATCH can advance revision during analysis.
   let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const arrival=new Promise<void>(resolve=>arrived=resolve);
   await page.route('**/api/runs',async route=>{arrived();await held;await route.continue();},{times:1});await page.locator('#agent-query').fill('평균 이온 에너지가 뭐야?');await page.locator('#agent-query-form [type="submit"]').click();await arrival;
   const patched=page.waitForResponse(response=>response.url().endsWith(`/turns/${first.id}/ui`)&&response.request().method()==='PATCH');await page.locator('.agent-fit-card-selectable').first().focus();await page.keyboard.press('Space');expect((await patched).status()).toBe(200);release();await waitForTurns(page,2);await expect(page.locator('#agent-query')).toHaveValue('');const afterUi=await workspace(request,api);expect(afterUi.conversation.turns).toHaveLength(2);expect(afterUi.conversation.turns[0].ui.selectedCandidateRunId).toBeNull();
   const savedAnswer=digest(afterUi.conversation.turns.map(turn=>turn.answerSnapshot));const searchesBeforeSecondReload=runSearchRequests;await page.reload();await waitForTurns(page,2);expect(runSearchRequests).toBe(searchesBeforeSecondReload);expect(digest((await workspace(request,api)).conversation.turns.map(turn=>turn.answerSnapshot))).toBe(savedAnswer);

   await page.locator(`[data-turn-id="${first.id}"] [data-action="open-experiment-record"]`).first().click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('input[name="adoptedRunId"]').first()).toBeVisible();const available=await page.locator('input[name="adoptedRunId"]').count();expect(available).toBeGreaterThan(0);const ids=await page.locator('input[name="adoptedRunId"]').evaluateAll(inputs=>inputs.map(input=>(input as HTMLInputElement).value));await page.getByLabel(`${ids[0]} 채택`,{exact:true}).check();const extraIds=ids.slice(1,3);for(const id of extraIds)await page.getByLabel(`${id} 추가 후보`,{exact:true}).check();await page.getByRole('button',{name:'다음: 후보별 판단'}).click();
   for(const [index,id] of extraIds.entries())await page.getByLabel(`${id} ${index===0?'반려':'보류'}`,{exact:true}).check();const memo='<img src=x onerror=alert(1)> actual persistence memo';await page.getByRole('textbox',{name:'후보별 판단 메모 선택'}).first().fill(memo);await page.getByRole('textbox',{name:'공통 실험 코멘트 필수'}).fill('actual ordinary EXP');await page.getByRole('textbox',{name:'작성자 별칭 선택'}).fill('Task10 actual');await page.getByRole('button',{name:'이전: 후보 구성'}).click();await page.getByRole('button',{name:'표',exact:true}).click();await page.getByRole('button',{name:'다음: 후보별 판단'}).click();await expect(page.getByRole('textbox',{name:'후보별 판단 메모 선택'}).first()).toHaveValue(memo);
   const expResponse=page.waitForResponse(response=>response.url().endsWith('/api/decisions')&&response.request().method()==='POST');await page.getByRole('button',{name:'실험 기록 저장',exact:true}).click();expect((await expResponse).status()).toBe(200);await expect(page.getByRole('dialog')).toHaveCount(0);const exp=(await decisions(request,api))[0];expect(exp.version).toBe(2);if(exp.version!==2)throw Error('Expected ordinary EXP');expect(exp.candidates.filter(candidate=>candidate.decision==='ADOPT')).toHaveLength(1);expect(exp.candidates).toHaveLength(1+extraIds.length);expect(exp.candidates[0].note).toBe(memo);expect(exp.targetRunRef).toEqual(refOf(first.answerRunRefs.find(ref=>ref.runId===ids[0])!));
   await navigate(page,'archive');await expect(page.locator('.archive-row')).toHaveCount(1);await page.locator('.archive-row').click();await expect(page.getByText(memo,{exact:true})).toBeVisible();expect(await page.locator('img,[onerror]').count()).toBe(0);await page.keyboard.press('Escape');await page.getByRole('textbox',{name:'작성자',exact:true}).fill(' Task10 actual ');await page.getByRole('button',{name:'필터 적용'}).click();await navigate(page,'agent');await navigate(page,'archive');await expect(page.getByRole('textbox',{name:'작성자',exact:true})).toHaveValue('Task10 actual');await page.reload();await expect(page.locator('.archive-row')).toHaveCount(0);await navigate(page,'archive');await expect(page.locator('.archive-row')).toHaveCount(1);

   await navigate(page,'analysis');await expect(page.locator('.analysis-run-title h2')).toBeVisible();const targetId=(await page.locator('.analysis-run-title h2').textContent())!;const preserved=(await workspace(request,api)).candidateReference;
   await page.getByRole('button',{name:'이 Run으로 Agent에게 질문',exact:true}).first().click();await waitForTurns(page,2);const analysisReference=await workspace(request,api);expect(analysisReference.candidateReference).toEqual(preserved);expect(analysisReference.conversation.activeRun?.runId).toBe(targetId);expect(analysisReference.conversation.turns).toHaveLength(2);
   await navigate(page,'analysis');await expect(page.locator('.analysis-run-title h2')).toHaveText(targetId);await page.getByRole('button',{name:'실험 기록',exact:true}).click();await page.getByRole('radio',{name:/보류/}).check();await page.getByRole('textbox',{name:/판단 근거 코멘트/}).fill('actual independent REV');await page.getByRole('textbox',{name:'작성자 별칭 선택'}).fill('Task10 actual');const comparisons=page.locator('input[name="comparedRunIds"]');if(await comparisons.count())await comparisons.first().check();const revResponse=page.waitForResponse(response=>response.url().endsWith('/api/decisions')&&response.request().method()==='POST');await page.getByRole('button',{name:'코멘트와 결정 저장'}).click();expect((await revResponse).status()).toBe(200);await expect(page.getByRole('dialog')).toHaveCount(0);const records=await decisions(request,api);expect(records).toHaveLength(2);const rev=records.find(record=>record.version!==2)!;expect(rev.decision).toBe('HOLD');expect(rev.targetRunRef).toEqual(analysisReference.conversation.activeRun);if(rev.version===2)throw Error('Expected independent REV');expect(rev.runSnapshots[0].runVersionId).toBe(rev.targetRunRef.runVersionId);

   // Another real writer advances revision: the rejected UI submission must retain the question for retry.
   const beforeExternalUi=await workspace(request,api);await json(await request.patch(`${api}/api/workspace/turns/${first.id}/ui`,{data:{stateToken:beforeExternalUi.stateToken,ui:{lookupExpanded:true}}}));await navigate(page,'agent');const failedQuestion='평균 이온 에너지가 뭐야? 다시 검토';await page.locator('#agent-query').fill(failedQuestion);await page.locator('#agent-query-form [type="submit"]').click();await expect(page.locator('.agent-conversation .alert--danger')).toContainText('Workspace revision has changed');await expect(page.locator('#agent-query')).toHaveValue(failedQuestion);await waitForTurns(page,2);expect((await workspace(request,api)).conversation.turns).toHaveLength(2);await page.reload();await waitForTurns(page,2);

   // Replay exact successful requests against the real server; changed payloads with the same key conflict.
   const expWrite=writes.find(write=>write.path==='/api/decisions'&&(write.body as DecisionWrite).record.version===2)!;const replay=await request.post(`${api}/api/decisions`,{data:expWrite.body,headers:{'Idempotency-Key':expWrite.key}});expect(replay.status()).toBe(200);expect((await replay.json() as DecisionRecord).reviewId).toBe(exp.reviewId);expect(await decisions(request,api)).toHaveLength(2);
   const changed=structuredClone(expWrite.body) as DecisionWrite;changed.record.comment='different retry';if(changed.record.version===2)changed.record.overallComment=changed.record.comment;const conflict=await request.post(`${api}/api/decisions`,{data:changed,headers:{'Idempotency-Key':expWrite.key}});expect(conflict.status()).toBe(409);expect((await conflict.json()).code).toBe('IDEMPOTENCY_CONFLICT');
   const turnWrite=writes.find(write=>write.path==='/api/workspace/turns')!;const current=await workspace(request,api);const turnReplay=await json<WorkspaceView>(await request.post(`${api}/api/workspace/turns`,{data:turnWrite.body,headers:{'Idempotency-Key':turnWrite.key}}));expect(turnReplay.stateToken).toEqual(current.stateToken);expect(turnReplay.conversation.turns).toHaveLength(2);
   const staleReference=await request.put(`${api}/api/workspace/reference`,{data:{stateToken:(turnWrite.body as TurnWrite).stateToken,candidateReference:null,activeRun:null}});expect(staleReference.status()).toBe(409);expect((await staleReference.json()).code).toBe('STALE_CONTEXT');

   await navigate(page,'agent');await page.getByRole('button',{name:'새 대화',exact:true}).click();await expect(page.locator('.agent-welcome')).toBeVisible();const cleared=await workspace(request,api);expect(cleared.conversation.turns).toEqual([]);expect(cleared.candidateReference).toBeNull();expect(cleared.conversation.activeRun).toBeNull();expect(await decisions(request,api)).toHaveLength(2);expect(cleared.stateToken.workspaceEpoch).toBe(current.stateToken.workspaceEpoch);expect(cleared.stateToken.conversationEpoch).toBe(current.stateToken.conversationEpoch+1);
   const oldTurn=await request.post(`${api}/api/workspace/turns`,{data:turnWrite.body,headers:{'Idempotency-Key':turnWrite.key}});expect(oldTurn.status()).toBe(409);expect((await oldTurn.json()).code).toBe('STALE_CONTEXT');
   await navigate(page,'archive');await expect(page.locator('.archive-row')).toHaveCount(2);if(width<760)await page.getByRole('button',{name:'메뉴 열기'}).click();await page.getByRole('button',{name:'데모 데이터 초기화'}).click();await expect(page.getByRole('alertdialog')).toBeVisible();await page.getByRole('alertdialog').getByRole('button',{name:'초기화',exact:true}).click();await expect(page.getByRole('alertdialog')).toHaveCount(0);await expect(page.locator('.archive-row')).toHaveCount(0);const reset=await workspace(request,api);expect(reset.stateToken.workspaceEpoch).toBe(cleared.stateToken.workspaceEpoch+1);expect(reset.conversation.turns).toEqual([]);expect(reset.candidateReference).toBeNull();expect(reset.conversation.activeRun).toBeNull();expect(await decisions(request,api)).toEqual([]);
   const oldRecord=await request.post(`${api}/api/decisions`,{data:expWrite.body,headers:{'Idempotency-Key':expWrite.key}});expect(oldRecord.status()).toBe(409);expect((await oldRecord.json()).code).toBe('STALE_CONTEXT');expect((await json<RunSummary[]>(await request.get(`${api}/api/runs`))).length).toBe(initialRunCount);expect(errors).toEqual([]);
   await info.attach('workspace-decision-summary',{body:JSON.stringify({width,actualHttp:true,registeredRuns:initialRunCount,ordinaryEXP:true,independentREV:true,referencePreserved:true,uiReload:true,uiRevisionDuringSubmit:true,idempotentReplay:true,stale409:true,staleSubmitRetainsQuestion:true,reloadWithoutRunSearch:true,newConversationKeepsRecords:true,resetClearsRecords:true,runAndCatalogHashesUnchanged:true}),contentType:'application/json'});
  });
 });
}
