package com.kplasma.analysisagent.agent;

import com.kplasma.analysisagent.contract.RunDto.RunRef;
import com.kplasma.analysisagent.contract.WorkspaceDto.AgentResponse;
import com.kplasma.analysisagent.workspace.SnapshotValidator;
import java.util.*;

/** Validate the public schema and reference inventory without fetching full Runs per nested ref. */
final class AnswerV2Validator {
    private final SnapshotValidator check;
    private static final String CODE="INVALID_AGENT_REQUEST";
    private static final Set<String> CONDITIONS=Set.of("pressure","sourcePower","biasPower");
    private static final Set<String> METRICS=Set.of("meanIonEnergy","ionFlux","iedWidth");
    private static final Set<String> REASONS=Set.of("MISSING_VALUE","MISSING_BASELINE","MISSING_TARGET","MISSING_BOTH","ZERO_BASELINE","INVALID_VALUE","UNIT_NOT_COMPARABLE","NUMERIC_OVERFLOW","INSUFFICIENT_DATA");
    AnswerV2Validator(SnapshotValidator check){this.check=check;}
    private void require(boolean value,String message){check.require(value,CODE,message);}
    private Map<?,?> object(Object value){require(value instanceof Map<?,?>,"Expected object");return (Map<?,?>)value;}
    private List<?> array(Object value){require(value instanceof List<?>,"Expected array");return (List<?>)value;}
    private void fields(Map<?,?> value,String... fields){require(value.keySet().equals(Set.of(fields)),"Unexpected or missing fields: "+value.keySet());}
    private String text(Object value){require(value instanceof String&&!((String)value).isBlank(),"Nonempty string required");return (String)value;}
    private void enumeration(Object value,String... allowed){require(Set.of(allowed).contains(String.valueOf(value)),"Unknown enum");}
    private boolean finite(Object value){return value instanceof Number n&&Double.isFinite(n.doubleValue());}
    private void nullableNumber(Object value){require(value==null||finite(value),"Finite number or null required");}
    private List<String> strings(Object value){return array(value).stream().map(this::text).toList();}
    private void unique(List<?> values){require(new HashSet<>(values).size()==values.size(),"Duplicate array item");}
    private RunRef ref(Object value){var map=object(value);fields(map,"runId","runVersionId");return new RunRef(text(map.get("runId")),text(map.get("runVersionId")));}
    private List<RunRef> refs(Object value){return array(value).stream().map(this::ref).toList();}
    private void scalar(Object value){var map=object(value);fields(map,"value","unit","status","reason","sourceValue");text(map.get("unit"));nullableNumber(map.get("value"));enumeration(map.get("status"),"AVAILABLE","UNAVAILABLE");
        if("AVAILABLE".equals(map.get("status")))require(finite(map.get("value"))&&map.get("reason")==null,"Available scalar requires value and null reason");
        else require(map.get("value")==null&&REASONS.contains(String.valueOf(map.get("reason"))),"Unavailable scalar requires null value and reason");
        if(map.get("sourceValue")!=null){var source=object(map.get("sourceValue"));fields(source,"value","unit");nullableNumber(source.get("value"));text(source.get("unit"));}}
    private void dataMap(Object value,Set<String> keys){var map=object(value);require(map.keySet().equals(keys),"Scalar map keys mismatch");map.values().forEach(this::scalar);}
    void answer(AgentResponse answer,String originalQuestion){
        var snapshot=answer.answerSnapshot();var requiredFields=new HashMap<>(snapshot);requiredFields.remove("unitAssumptions");fields(requiredFields,"implementationId","graphVersion","schemaVersion","kind","summary","originalQuestion","toolSelection","resolvedInputs","result","answer","contextProvenance","inputHistory","usedRunRefs","versions");
        require("v1".equals(snapshot.get("graphVersion"))&&snapshot.get("schemaVersion") instanceof Number n&&n.doubleValue()==2,"Unknown answer version");text(snapshot.get("summary"));require(Objects.equals(snapshot.get("originalQuestion"),originalQuestion),"Original question mismatch");
        String kind=text(snapshot.get("kind"));enumeration(kind,"forward_lookup","reverse_search","compare_runs","generate_answer");var selection=object(snapshot.get("toolSelection"));fields(selection,"call_id","name","arguments");text(selection.get("call_id"));require(kind.equals(selection.get("name")),"Tool selection mismatch");object(selection.get("arguments"));object(snapshot.get("resolvedInputs"));object(snapshot.get("contextProvenance"));array(snapshot.get("inputHistory"));object(snapshot.get("versions"));
        require(refs(snapshot.get("usedRunRefs")).equals(answer.usedRunRefs()),"Snapshot inventory mismatch");
        if(snapshot.containsKey("unitAssumptions"))unitAssumptions(snapshot,kind);
        var result=object(snapshot.get("result"));require(kind.equals(result.get("kind"))&&Objects.equals(answer.status(),result.get("resultStatus")),"Result/status mismatch");
        String intent=Map.of("forward_lookup","FORWARD_LOOKUP","reverse_search","REVERSE_SEARCH","compare_runs","RUN_COMPARISON","generate_answer","GENERAL_ANSWER").get(kind);require(intent.equals(answer.intent()),"Intent/tool mismatch");
        if(kind.equals("compare_runs")){require(answer.candidates().isEmpty()&&answer.explanation()==null,"Comparison has no legacy candidates/explanation");comparison(result,answer.usedRunRefs(),false);comparisonAnswer(snapshot.get("answer"),result);}
        else require(snapshot.get("answer")==null,"Only comparisons have an answer object");
        if(kind.equals("generate_answer")){fields(result,"kind","resultStatus","markdown","knowledgeBasis","usedRunRefs");require("ANSWER_READY".equals(result.get("resultStatus"))&&"LLM_GENERAL_KNOWLEDGE".equals(result.get("knowledgeBasis")),"Invalid general answer");text(result.get("markdown"));require(answer.usedRunRefs().isEmpty()&&refs(result.get("usedRunRefs")).isEmpty()&&answer.candidates().isEmpty()&&answer.explanation()==null,"General answer cannot depend on Run refs");require(object(snapshot.get("resolvedInputs")).isEmpty()&&object(snapshot.get("contextProvenance")).isEmpty()&&object(selection.get("arguments")).isEmpty(),"General inputs must be empty");}
    }
    private void unitAssumptions(Map<?,?> snapshot,String kind){
        var assumptions=array(snapshot.get("unitAssumptions"));
        require(assumptions.isEmpty()||Set.of("forward_lookup","reverse_search").contains(kind),"Only searches have unit assumptions");
        var units=Map.of("pressure","mTorr","sourcePower","W","biasPower","W","meanIonEnergy","eV","ionFlux","10¹⁸ m⁻²s⁻¹","iedWidth","eV");
        var inputs=object(snapshot.get("resolvedInputs"));Map<String,Map<?,?>> quantities=new HashMap<>();
        if(inputs.get("conditions") instanceof Map<?,?> conditions)conditions.forEach((key,value)->quantities.put(String.valueOf(key),object(value)));
        for(String group:List.of("constraints","goals"))if(inputs.get(group) instanceof List<?> rows)for(Object value:rows){var row=object(value);if(row.get("value")!=null||row.get("min")!=null||row.get("max")!=null)quantities.put(text(row.get("metric")),row);}
        Set<String> seen=new HashSet<>();
        for(Object value:assumptions){var row=object(value);fields(row,"metric","unit");String metric=text(row.get("metric"));require(seen.add(metric)&&units.containsKey(metric)&&units.get(metric).equals(row.get("unit"))&&quantities.containsKey(metric)&&Objects.equals(quantities.get(metric).get("unit"),row.get("unit")),"Invalid unit assumption");}
    }
    void comparison(Map<?,?> result,List<RunRef> inventory,boolean partial){
        Set<String> expected=new HashSet<>(Set.of("kind","resultStatus","mode","metricIds","baselineKey","trendAxis","runs","comparisons","summaries","trends","observations","usedRunRefs","numericPolicyVersion","aggregationPolicyVersion"));if(partial){expected.add("schemaVersion");expected.add("explanationComplete");require(result.get("schemaVersion") instanceof Number n&&n.doubleValue()==2&&Boolean.FALSE.equals(result.get("explanationComplete")),"Invalid partial version");}require(result.keySet().equals(expected),"Comparison fields mismatch");
        require("compare_runs".equals(result.get("kind"))&&"v1".equals(result.get("numericPolicyVersion"))&&"multi-run-1".equals(result.get("aggregationPolicyVersion")),"Unknown comparison policy");enumeration(result.get("resultStatus"),"COMPARISON_READY","COMPARISON_PARTIAL","NO_COMPARABLE_DATA");enumeration(result.get("mode"),"values","pair","overview","baseline","trend");var metrics=strings(result.get("metricIds"));require(!metrics.isEmpty()&&METRICS.containsAll(metrics),"Invalid metrics");unique(metrics);
        require(inventory.size()>=2&&refs(result.get("usedRunRefs")).equals(inventory),"Comparison inventory mismatch");unique(inventory);List<RunRef> runRefs=new ArrayList<>();Set<String> keys=new HashSet<>();
        for(Object value:array(result.get("runs"))){var row=object(value);fields(row,"key","ref","conditions","metrics","quality");require(keys.add(text(row.get("key"))),"Duplicate Run alias");runRefs.add(ref(row.get("ref")));dataMap(row.get("conditions"),CONDITIONS);dataMap(row.get("metrics"),new HashSet<>(metrics));var quality=object(row.get("quality"));fields(quality,"convergenceStatus","qualityStatus","catalogStatus");quality.values().forEach(this::text);}
        require(runRefs.equals(inventory),"Run order/inventory mismatch");Object baseline=result.get("baselineKey"),axis=result.get("trendAxis");require(baseline==null||keys.contains(baseline),"Invalid baseline");require(axis==null||CONDITIONS.contains(axis),"Invalid axis");
        Set<String> comparisonIds=new HashSet<>(),summaryIds=new HashSet<>(),trendIds=new HashSet<>();
        for(Object value:array(result.get("comparisons"))){var row=object(value);fields(row,"id","kind","leftKey","rightKey","metric","difference","percentChange","direction");require(comparisonIds.add(text(row.get("id")))&&keys.contains(row.get("leftKey"))&&keys.contains(row.get("rightKey"))&&!Objects.equals(row.get("leftKey"),row.get("rightKey"))&&metrics.contains(row.get("metric")),"Comparison identity mismatch");enumeration(row.get("kind"),"absolute_difference","baseline_delta","adjacent_delta");enumeration(row.get("direction"),"increase","decrease","unchanged","not_applicable","unavailable");scalar(row.get("difference"));if("absolute_difference".equals(row.get("kind")))require(row.get("percentChange")==null,"Absolute difference has no signed percent");else scalar(row.get("percentChange"));}
        for(Object value:array(result.get("summaries"))){var row=object(value);fields(row,"id","metric","availableCount","minimum","minimumKeys","maximum","maximumKeys","range");require(summaryIds.add(text(row.get("id")))&&metrics.contains(row.get("metric")),"Summary mismatch");require(row.get("availableCount") instanceof Number n&&n.doubleValue()==n.intValue()&&n.intValue()>=0&&n.intValue()<=inventory.size(),"Invalid available count");for(String field:List.of("minimum","maximum","range"))scalar(row.get(field));require(keys.containsAll(strings(row.get("minimumKeys")))&&keys.containsAll(strings(row.get("maximumKeys"))),"Unknown extrema Run");}
        for(Object value:array(result.get("trends"))){var row=object(value);fields(row,"id","metric","axis","fixedConditions","orderedKeys","comparisonIds","direction");require(trendIds.add(text(row.get("id")))&&metrics.contains(row.get("metric"))&&CONDITIONS.contains(row.get("axis")),"Trend mismatch");Set<String> fixed=new HashSet<>(CONDITIONS);fixed.remove(row.get("axis"));dataMap(row.get("fixedConditions"),fixed);require(keys.containsAll(strings(row.get("orderedKeys")))&&comparisonIds.containsAll(strings(row.get("comparisonIds"))),"Unknown trend reference");enumeration(row.get("direction"),"increasing","decreasing","constant","non_monotonic","insufficient_data","unavailable");}
        Set<String> ids=new HashSet<>();for(Object value:array(result.get("observations"))){var row=object(value);fields(row,"id","source","text");require(ids.add(text(row.get("id"))),"Duplicate observation");text(row.get("text"));var source=object(row.get("source"));fields(source,"kind","key","metric");require(metrics.contains(source.get("metric")),"Observation metric mismatch");String sourceKind=text(source.get("kind"));Set<String> allowed=switch(sourceKind){case "run"->keys;case "comparison"->comparisonIds;case "summary"->summaryIds;case "trend"->trendIds;default->Set.of();};require(allowed.contains(source.get("key")),"Observation source mismatch");}
    }
    private void comparisonAnswer(Object value,Map<?,?> result){var answer=object(value);fields(answer,"kind","status","knowledgeBasis","observationIds","interpretations","limitations");require("comparison_answer".equals(answer.get("kind"))&&"COMPLETE".equals(answer.get("status"))&&"VERIFIED_RUNS_AND_LLM_GENERAL_KNOWLEDGE".equals(answer.get("knowledgeBasis")),"Invalid comparison answer");Set<String> ids=new HashSet<>();for(Object observation:array(result.get("observations")))ids.add(text(object(observation).get("id")));require(ids.containsAll(strings(answer.get("observationIds")))&&(!strings(answer.get("observationIds")).isEmpty()||!array(answer.get("interpretations")).isEmpty()),"Unknown answer observation");for(Object valueItem:array(answer.get("interpretations"))){var item=object(valueItem);fields(item,"text","observationIds","assumptions");text(item.get("text"));require(!strings(item.get("observationIds")).isEmpty()&&ids.containsAll(strings(item.get("observationIds"))),"Unknown interpretation observation");strings(item.get("assumptions"));}strings(answer.get("limitations"));}
}
