import {expect,test} from 'vitest';
import {createRecord,executeFallback,toRunSummary,type AgentContext,type FullRun,type RunRef} from '../src';
import {syntheticRun} from './support/synthetic-runs';
const a={...syntheticRun(),runId:'A',runVersionId:'old-a'};const latestA={...a,runVersionId:'latest-a'};const b={...syntheticRun(),runId:'B',runVersionId:'old-b'};
const ref=(r:RunRef)=>({runId:r.runId,runVersionId:r.runVersionId});
const context=(current:FullRun[],latestReferences:RunRef[])=>({candidateRunsLatest:current.map(toRunSummary),referenceRunsByVersion:new Map([a,b,latestA].map(r=>[r.runVersionId,r])),latestCandidateReferences:latestReferences,decisionRecords:[],hydrateFullRun:async(r:RunRef)=>[a,b,latestA].find(run=>run.runVersionId===r.runVersionId)!} as AgentContext);
test('mentioned candidate set prefers latest group B over current reference A',async()=>{const answer=await executeFallback({text:'이 후보들 중 비용 때문에 많이 반려된 건 제외해줘',candidateReferences:[ref(a)]},context([latestA,b],[ref(b)]));expect(answer.answerSnapshot.reference).toEqual({kind:'단일 Run',ids:['B']});expect(answer.usedRunRefs).toEqual([ref(b)]);});
test('overlapping display ID resolves chosen latest-group historical version, never current version',async()=>{const answer=await executeFallback({text:'이 후보들 중 비용 때문에 많이 반려된 건 제외해줘',candidateReferences:[ref(latestA)]},context([latestA,b],[ref(a)]));expect(answer.usedRunRefs).toEqual([ref(a)]);});
test.each([{threshold:1},{undo:true}])('supplied retry reference overrides newer latest group: %j',async options=>{const answer=await executeFallback({text:'이 후보들 중 비용 때문에 많이 반려된 건 제외해줘',candidateReferences:[ref(a)],clarification:{...options,useSuppliedMemoryReference:true}},context([latestA,b],[ref(b)]));expect(answer.answerSnapshot.reference).toEqual({kind:'단일 Run',ids:['A']});expect(answer.usedRunRefs).toEqual([ref(a)]);});
test('numeric memory search still searches whole latest collection',async()=>{const answer=await executeFallback({text:'Ion Flux 1 이상인 후보를 찾되 비용 때문에 반려된 건 제외해줘',candidateReferences:[ref(a)]},context([latestA,b],[ref(a)]));expect(answer.candidates).toEqual(expect.arrayContaining([ref(latestA),ref(b)]));});
test('role metadata separates numeric latest candidate from historical selected reference and supports explicit retry',async()=>{const ctx=context([latestA,b],[ref(b)]);const first=await executeFallback({text:'Ion Flux 1 이상인 후보를 찾되 비용 때문에 반려된 건 제외해줘',candidateReferences:[ref(a)]},ctx);expect(first.answerSnapshot.candidateRunRefs).toEqual(first.candidates);expect((first.answerSnapshot.memoryRequest as {referenceRunRefs:RunRef[]}).referenceRunRefs).toEqual([ref(a)]);const persisted=JSON.parse(JSON.stringify(first.answerSnapshot));const retried=await executeFallback({text:persisted.memoryRequest.text,candidateReferences:persisted.memoryRequest.referenceRunRefs,clarification:{threshold:2,useSuppliedMemoryReference:true}},context([latestA,b],[ref(b)]));expect((retried.answerSnapshot.memoryRequest as {referenceRunRefs:RunRef[]}).referenceRunRefs).toEqual([ref(a)]);expect(retried.answerSnapshot.candidateRunRefs).toEqual(expect.arrayContaining([ref(latestA),ref(b)]));});


test('numeric excluded identity is latest while ID-based historical rejection and explicit retry keep old reference',async()=>{
 const ctx=context([latestA,b],[]);const raw=createRecord({targetRunId:a.runId,decision:'REJECT',comment:'비용 예산 초과',analysisType:'FORWARD'},[a,b]);ctx.decisionRecords=[{...raw,decision:'REJECT',targetRunRef:ref(a),comparedRunRefs:[],runSnapshots:raw.runSnapshots.map(snapshot=>({...snapshot,runVersionId:a.runVersionId}))}];const text='Ion Flux 1 이상인 후보를 찾되 비용 때문에 반려된 건 제외해줘';const first=await executeFallback({text,candidateReferences:[ref(a)],clarification:{threshold:1}},ctx);expect(first.answerSnapshot.excludedRunRefs).toEqual([ref(latestA)]);expect(first.candidates).not.toContainEqual(ref(latestA));expect(first.usedRunRefs).toEqual(expect.arrayContaining([ref(a),ref(latestA)]));expect((first.answerSnapshot.memoryRequest as {referenceRunRefs:RunRef[]}).referenceRunRefs).toEqual([ref(a)]);
 const undo=await executeFallback({text,candidateReferences:[ref(a)],clarification:{threshold:1,undo:true,useSuppliedMemoryReference:true}},ctx);expect(undo.answerSnapshot.excludedRunRefs).toEqual([]);expect(undo.candidates).toContainEqual(ref(latestA));expect((undo.answerSnapshot.memoryRequest as {referenceRunRefs:RunRef[]}).referenceRunRefs).toEqual([ref(a)]);
 const scoped=await executeFallback({text:'이 후보들 중 비용 반려 1건 이상 제외해줘',candidateReferences:[ref(a)]},ctx);expect(scoped.answerSnapshot.excludedRunRefs).toEqual([ref(a)]);
});
