import {useRef,type InputHTMLAttributes} from 'react';
import type {JobView} from 'agent';
import type {useImportBatch} from './useImportBatch';
export const jobLabels:Record<string,string>={QUEUED:'대기 중',PROCESSING:'처리 중',READY:'파싱 완료',DUPLICATE:'중복 Run',INCOMPLETE:'필수 파일 누락',PARSE_FAILED:'파싱 실패',INTERRUPTED:'서버 중단',SUCCESS:'완료',PARTIAL_SUCCESS:'일부 완료',FAILED:'실패'};
export const canReprocess=(job:JobView)=>!['QUEUED','PROCESSING'].includes(job.status);
export function UploadControls({imports,selectedJob,disabled=false}:{imports:ReturnType<typeof useImportBatch>;selectedJob:JobView|null;disabled?:boolean}){
 const folder=useRef<HTMLInputElement>(null),zip=useRef<HTMLInputElement>(null);const {batch,progress,pending,error}=imports;
 const uploading=pending&&!batch;const percent=progress?.total?Math.floor(progress.loaded/progress.total*100):null;
 const status=error?'오류':uploading?'파일 전송 중':batch?jobLabels[batch.status]:'등록 대기';
 const progressValue=uploading?percent:batch?.processedRuns;const progressMax=uploading?100:Math.max(batch?.totalRuns??0,1);
 return <section className="panel parsing-lab"><div className="parsing-copy"><span className="section-kicker">RESULT FILE IMPORT</span><h2>결과 파일 등록 상태</h2><p>선택한 원본 파일을 전송하고 Run별 파싱·중복·누락 상태를 확인합니다.</p><div className="mock-drop"><span aria-hidden="true">⇧</span><strong>폴더 또는 ZIP 결과 파일 선택</strong><small>폴더·ZIP 최대 2 GiB · 일반 파일 최대 64 MiB · 5,000파일</small></div></div><div className="parsing-control"><div className="parsing-scenarios"><button type="button" disabled={pending||disabled} onClick={()=>folder.current?.click()}>폴더 선택</button><button type="button" disabled={pending||disabled} onClick={()=>zip.current?.click()}>ZIP 선택</button><input ref={folder} type="file" multiple {...({webkitdirectory:''} as InputHTMLAttributes<HTMLInputElement>)} className="sr-only" aria-label="폴더 선택" disabled={pending||disabled} onChange={event=>{const files=Array.from(event.currentTarget.files??[]);event.currentTarget.value='';if(files.length)void imports.uploadFolder(files);}}/><input ref={zip} type="file" accept=".zip,application/zip" className="sr-only" aria-label="ZIP 선택" disabled={pending||disabled} onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(file)void imports.uploadZip(file);}}/></div><div className="parsing-status" aria-live="polite"><div><span className={`badge ${error||batch?.status==='FAILED'?'badge--danger':batch?.status==='SUCCESS'?'badge--success':'badge--warning'}`}>{status}</span><strong>{error|| (uploading?`${progress?.loaded??0}${progress?.total?` / ${progress.total}`:''} bytes 전송`:batch?`${batch.processedRuns} / ${batch.totalRuns} Run 처리`:'결과 폴더 또는 ZIP을 선택하세요.')}</strong></div>{error&&<p role="alert">{error}</p>}<div className="progress-track" role="progressbar" aria-label={uploading?'파일 전송률':'Run 처리 진행률'} aria-valuemin={0} aria-valuemax={progressMax} aria-valuenow={progressValue??undefined} aria-valuetext={uploading&&percent===null?'전송 바이트 집계 중':undefined}><span style={{width:`${uploading?(percent??0):batch?.totalRuns?batch.processedRuns/batch.totalRuns*100:0}%`}}/></div>{selectedJob&&canReprocess(selectedJob)&&<button className="button button--secondary button--small" type="button" disabled={pending||disabled} onClick={()=>void imports.reprocess(selectedJob.jobId)}>다시 처리</button>}{batch&&<ul>{batch.jobs.map(job=><li key={job.jobId}>{job.runId??job.jobId} · {jobLabels[job.status]}{job.reason?` · ${job.reason}`:''}</li>)}</ul>}</div></div></section>;
}
