import {useCallback,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import type {RunRef} from 'agent';
import {AnalysisPage,initialAnalysisState} from './features/analysis/AnalysisPage';
import {RunDetailDialog} from './features/analysis/RunDetail';
import {FlowPage} from './features/flow/FlowPage';
import {Toast,type ToastMessage} from './components/Toast';
import './prototype/styles.css';
export type View='agent'|'analysis'|'archive'|'catalog'|'flow';
export interface ShellContext {navigate:(view:View)=>void;openRunDetail:(ref:RunRef)=>void;notify:(text:string,tone?:string)=>void}
export interface AppProps {pages?:Partial<Record<View,(context:ShellContext)=>ReactNode>>;decisionCount?:number;onReference?:(ref:RunRef)=>void;onDecision?:(ref:RunRef)=>void;onReset?:()=>void;modal?:ReactNode}
const labels:Record<View,string>={agent:'분석 Agent',analysis:'실험 데이터 탐색',archive:'의사결정 기록',catalog:'Run 데이터 관리',flow:'사용 방법'};
const icons:Record<View,string>={agent:'⌁',analysis:'⌗',archive:'▤',catalog:'◫',flow:'?'};
function PendingPage(){return <section className="loading-state" aria-label="프로토타입 준비 중"><div className="loading-mark" aria-hidden="true">K</div><h1>K-PLASMA Decision Studio</h1><p>검증된 Run 데이터를 불러오는 중입니다.</p></section>;}
export function App({pages={},decisionCount=0,onReference,onDecision,onReset,modal}:AppProps={}){
 const [activeView,setActiveView]=useState<View>('agent');const [mobileOpen,setMobileOpen]=useState(false);const [navigation,setNavigation]=useState(0);const root=useRef<HTMLElement>(null);const tools=useRef<HTMLDetailsElement>(null);
 const [analysisState,setAnalysisState]=useState(initialAnalysisState);const [detail,setDetail]=useState<RunRef|null>(null);const [toasts,setToasts]=useState<ToastMessage[]>([]);const sequence=useRef(0);
 const notify=useCallback((text:string,tone='success')=>setToasts(items=>[...items,{id:++sequence.current,text,tone}]),[]);const removeToast=useCallback((id:number)=>setToasts(items=>items.filter(item=>item.id!==id)),[]);
 function navigate(view:View){setActiveView(view);setMobileOpen(false);setNavigation(n=>n+1);if(tools.current)tools.current.open=view==='catalog'||view==='flow';}
 useLayoutEffect(()=>{if(!navigation)return;window.scrollTo({top:0,behavior:'auto'});root.current?.focus({preventScroll:true});},[navigation]);
 const context:ShellContext={navigate,openRunDetail:ref=>setDetail({runId:ref.runId,runVersionId:ref.runVersionId}),notify};
 function nav(view:View){return <button key={view} className={`nav-item ${activeView===view?'is-active':''}`} type="button" data-view={view} aria-current={activeView===view?'page':undefined} onClick={()=>navigate(view)}><span className="nav-icon" aria-hidden="true">{icons[view]}</span><span>{labels[view]}</span>{view==='archive'&&<span className="nav-badge" id="archive-count" aria-label="저장된 결정 수">{decisionCount}</span>}</button>;}
 let page=pages[activeView]?.(context);
 if(page===undefined)page=activeView==='analysis'?<AnalysisPage state={analysisState} onStateChange={setAnalysisState} onReference={onReference} onDecision={onDecision}/>:activeView==='flow'?<FlowPage decisionCount={decisionCount} onNavigate={navigate}/>:<PendingPage/>;
 return <><a className="skip-link" href="#view-root">본문으로 건너뛰기</a><div id="app" className="app-shell"><aside id="sidebar" className={`sidebar ${mobileOpen?'is-open':''}`} aria-label="주요 메뉴"><div className="brand"><span className="brand-mark" aria-hidden="true">K</span><span className="brand-copy"><strong>K-PLASMA</strong><small>Decision Studio</small></span></div><nav className="nav-stack" aria-label="분석 메뉴"><p className="nav-label">WORKSPACE</p>{(['agent','analysis','archive'] as View[]).map(nav)}<details ref={tools} className="nav-tools"><summary className="nav-item"><span className="nav-icon" aria-hidden="true">···</span><span>도구 및 도움말</span><span className="nav-chevron" aria-hidden="true">⌄</span></summary><div className="nav-tool-list">{(['catalog','flow'] as View[]).map(nav)}</div></details></nav><div className="sidebar-foot"><div className="system-health"><span className="status-dot status-dot--success" aria-hidden="true"/><span><strong>로컬 모드</strong><small>목업 데이터 · 백엔드 미연결</small></span></div><button className="text-button" id="reset-demo" type="button" onClick={onReset}>데모 데이터 초기화</button></div></aside><div className="app-main"><header id="topbar" className="topbar"><button className="icon-button mobile-menu" id="mobile-menu" type="button" aria-controls="sidebar" aria-expanded={mobileOpen} aria-label="메뉴 열기" onClick={()=>setMobileOpen(open=>!open)}>☰</button><div className="breadcrumb" aria-label="현재 위치"><span>Workspace</span><span aria-hidden="true">/</span><strong id="current-view-label">{labels[activeView]}</strong></div><div className="topbar-actions"><span className="context-chip"><span className="status-dot status-dot--success"/>실제 Run 150개 · 예측 없음</span><button className="avatar-button" type="button" aria-label="사용자: 익명">익명</button></div></header><main ref={root} id="view-root" className="view-root" tabIndex={-1}>{page}</main></div></div><div id="modal-root"/>{modal??(detail?<RunDetailDialog runRef={detail} onClose={()=>setDetail(null)}/>:null)}<Toast messages={toasts} onRemove={removeToast}/></>;
}
