import {Fragment,useEffect,useState,type CSSProperties} from 'react';
import type {Conditions,FullRun,RunRef,RunSummary} from 'agent';
import {analysisEngine} from '../../prototype/view-models';
import {compactNumber,renderAnalysisChartContent} from '../../prototype/charts';
import {fetchRuns,fetchRunVersion} from '../../api/runs';
type ConditionKey=keyof Conditions;
type Metric='ionFlux'|'meanIonEnergy'|'iedWidth';
export interface AnalysisState {analysisFixedKey:ConditionKey;analysisFixedValue:number;analysisMetric:Metric;analysisRunId:string;analysisTab:string}
export const initialAnalysisState:AnalysisState={analysisFixedKey:'biasPower',analysisFixedValue:600,analysisMetric:'meanIonEnergy',analysisRunId:'RUN-P06-S300-B0600',analysisTab:'distribution'};
interface Grid {fixedKey:ConditionKey;fixedValue:number;rowKey:ConditionKey;columnKey:ConditionKey;rows:number[];columns:number[];cells:{run:RunSummary|null;value:number|null;rowValue:number}[];range:{min:number|null;max:number|null}}
export interface AnalysisPageProps {runs?:RunSummary[];state?:AnalysisState;onStateChange?:(state:AnalysisState)=>void;onReference?:(ref:RunRef)=>void;onDecision?:(ref:RunRef)=>void}
export function AnalysisPage({runs:provided,state:external,onStateChange,onReference,onDecision}:AnalysisPageProps){
 const [local,setLocal]=useState(initialAnalysisState);const state=external??local;
 const update=(patch:Partial<AnalysisState>)=>{const next={...state,...patch};if(onStateChange)onStateChange(next);else setLocal(next);};
 const [loaded,setLoaded]=useState<RunSummary[]|null>(provided??null);const [selected,setSelected]=useState<FullRun|null>(null);const [error,setError]=useState('');
 useEffect(()=>{if(provided){setLoaded(provided);return;}const controller=new AbortController();fetchRuns(controller.signal).then(value=>{if(!controller.signal.aborted)setLoaded(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[provided]);
 const runs=loaded??[];const fixedValues=analysisEngine.getFixedValues(runs,state.analysisFixedKey) as number[];
 const fixedValue=fixedValues.includes(state.analysisFixedValue)?state.analysisFixedValue:fixedValues[0];
 const grid=analysisEngine.buildConditionGrid(runs,state.analysisFixedKey,fixedValue,state.analysisMetric) as Grid;
 const current=runs.find(run=>run.runId===state.analysisRunId&&run[state.analysisFixedKey]===fixedValue);
 const selectedSummary=current??runs.find(run=>run.pressure===(state.analysisFixedKey==='pressure'?fixedValue:6)&&run.sourcePower===(state.analysisFixedKey==='sourcePower'?fixedValue:300)&&run.biasPower===(state.analysisFixedKey==='biasPower'?fixedValue:600))??grid.cells.find(cell=>cell.run)?.run;
 useEffect(()=>{if(!selectedSummary)return;const controller=new AbortController();setError('');setSelected(null);fetchRunVersion(selectedSummary,controller.signal).then(value=>{if(!controller.signal.aborted)setSelected(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[selectedSummary?.runVersionId]);
 useEffect(()=>{if(selectedSummary&&(state.analysisRunId!==selectedSummary.runId||state.analysisFixedValue!==fixedValue))update({analysisRunId:selectedSummary.runId,analysisFixedValue:fixedValue});},[selectedSummary?.runVersionId,fixedValue]);
 function fixedKeyChanged(key:ConditionKey){const values=analysisEngine.getFixedValues(runs,key) as number[];update({analysisFixedKey:key,analysisFixedValue:selectedSummary&&values.includes(selectedSummary[key])?selectedSummary[key]:values[0]});}
 if(error)return <div className="analysis-chart-empty" role="alert">{error}</div>;
 if(loaded===null||selectedSummary&&!selected)return <section className="loading-state" aria-label="Run 데이터 준비 중"><p>검증된 Run 데이터를 불러오는 중입니다.</p></section>;
 if(!selected)return <div className="agent-detail-empty">실제 Run 데이터를 찾을 수 없습니다.</div>;
 const conditionMeta={pressure:{label:'Pressure',short:'P',unit:'mTorr'},sourcePower:{label:'Source Power',short:'S',unit:'W'},biasPower:{label:'Bias Power',short:'B',unit:'W'}};
 const selectedRef:RunRef={runId:selected.runId,runVersionId:selected.runVersionId};
 const analysisData={runs,meta:{actualRunCount:150}};
 const metricDefinition=analysisEngine.METRICS[state.analysisMetric];
 const tabs=[['distribution','분포','IED · IAD · IEAD'],['waveforms','파형','전류 · 전위'],['density','쉬스 밀도','위상 · 거리'],['convergence','수렴','잔차 추이']];
 const kpis=[['Mean ion energy',compactNumber(selected.metrics.meanIonEnergy),'eV'],['Ar+ flux',compactNumber(selected.metrics.ionFlux),'10¹⁸ m⁻²s⁻¹'],['Electron temp.',compactNumber(selected.analysis.electronTemperature),'eV'],['Electron density',compactNumber(selected.analysis.electronDensity),'#/cm³'],['DC offset',selected.analysis.dcOffset===null?'N/A':compactNumber(selected.analysis.dcOffset),'V'],['Peak-to-peak',selected.analysis.peakToPeak===null?'N/A':compactNumber(selected.analysis.peakToPeak),'V']];
return <><div className="page-header"><div><span className="eyebrow">ACTUAL EXPERIMENT ANALYTICS</span><h1>실험 결과를 조건별로 탐색합니다</h1><p>150개 실행 결과에서 실제 수치만 표시하며 중간 조건을 예측하거나 보간하지 않습니다.</p></div><div className="page-actions"><span className="trust-label"><span className="status-dot status-dot--success"></span>{analysisData.meta && analysisData.meta.actualRunCount ? analysisData.meta.actualRunCount : analysisData.runs.length} actual runs</span></div></div>
      <section className="panel analysis-control-panel"><div className="analysis-toolbar"><div><span className="section-kicker">CONDITION EXPLORER</span><h2>{conditionMeta[grid.fixedKey].label} {grid.fixedValue} {conditionMeta[grid.fixedKey].unit} 고정 · {conditionMeta[grid.rowKey].label} × {conditionMeta[grid.columnKey].label}</h2><p>고정 변수 하나를 선택하고 나머지 두 조건의 실제 Run만 비교합니다.</p></div><div className="analysis-selectors"><label><span>고정 변수</span><select id="analysis-fixed-key" value={state.analysisFixedKey} onChange={event=>fixedKeyChanged(event.target.value as ConditionKey)}><option value="pressure">Pressure</option><option value="sourcePower">Source Power</option><option value="biasPower">Bias Power</option></select></label><label><span>고정 값</span><select id="analysis-fixed-value" value={fixedValue} onChange={event=>update({analysisFixedValue:Number(event.target.value)})}>{fixedValues.map((value) => <Fragment key={value}><option value={value}>{value} {conditionMeta[state.analysisFixedKey].unit}</option></Fragment>)}</select></label><label><span>셀 표시 지표</span><select id="analysis-metric" value={state.analysisMetric} onChange={event=>update({analysisMetric:event.target.value as Metric})}>{(['ionFlux', 'meanIonEnergy', 'iedWidth'] as Metric[]).map((key) => <Fragment key={key}><option value={key}>{analysisEngine.METRICS[key].label}</option></Fragment>)}</select></label></div></div>
        <div className="analysis-overview"><div className="condition-map-wrap"><div className="condition-map-meta"><span>{metricDefinition.label}</span><strong>{analysisEngine.formatMetric(grid.range.min, state.analysisMetric)} – {analysisEngine.formatMetric(grid.range.max, state.analysisMetric)} {metricDefinition.unit}</strong><small>색상은 선택한 {grid.cells.filter((cell) => cell.run).length}개 실제 Run 범위 기준</small></div><div className="condition-map" style={{'--map-columns':grid.columns.length} as CSSProperties}><span className="map-corner">{conditionMeta[grid.rowKey].short} × {conditionMeta[grid.columnKey].short}</span>{grid.columns.map((value) => <Fragment key={value}><span className="map-axis map-axis--x">{value} {conditionMeta[grid.columnKey].unit}</span></Fragment>)}{grid.rows.map((rowValue) => <Fragment key={rowValue}><span className="map-axis map-axis--y">{rowValue}<small>{conditionMeta[grid.rowKey].unit}</small></span>{grid.cells.filter((cell) => cell.rowValue === rowValue).map((cell) => {
          if (!cell.run) return <Fragment key={`${rowValue}-${grid.cells.indexOf(cell)}`}><span className="condition-cell condition-cell--empty" aria-label="실행된 Run 없음">N/A<small>실제 Run 없음</small></span></Fragment>;
          const ratio = cell.value === null ? 0 : (cell.value - (grid.range.min ?? 0)) / Math.max((grid.range.max ?? 0) - (grid.range.min ?? 0), Number.EPSILON);
          return <Fragment key={cell.run.runId}><button className={`condition-cell ${cell.run.runId === selected.runId ? 'is-selected' : ''}`} type="button" data-action="analysis-select" onClick={()=>update({analysisRunId:cell.run!.runId})} data-run-id={cell.run.runId} style={{'--cell-strength':ratio.toFixed(3)} as CSSProperties} aria-label={`${cell.run.runId}, ${metricDefinition.label} ${analysisEngine.formatMetric(cell.value, state.analysisMetric)} ${metricDefinition.unit}`} aria-pressed={cell.run.runId === selected.runId}><strong>{analysisEngine.formatMetric(cell.value, state.analysisMetric)}</strong><small>{cell.run.runId.replace('RUN-', '')}</small></button></Fragment>;
        })}</Fragment>)}</div><div className="condition-map-legend"><span>Lower</span><i></i><span>Higher</span><b>■ 선택된 Run</b></div></div>
        <aside className="analysis-selection-card"><div className="analysis-run-title"><div><span className="section-kicker">SELECTED ACTUAL RUN</span><h2>{selected.runId}</h2></div><span className="badge badge--success">엔진 완료</span></div><div className="analysis-condition-row"><div><span>Pressure</span><strong>{selected.pressure}</strong><small>mTorr</small></div><div><span>Source</span><strong>{selected.sourcePower}</strong><small>W</small></div><div><span>Bias</span><strong>{selected.biasPower}</strong><small>W</small></div></div><div className="analysis-availability"><span className={`status-dot ${selected.analysis.hasDistribution ? 'status-dot--success' : ''}`}></span><div><strong>{selected.analysis.hasDistribution ? '분포·파형 원본 있음' : 'Bias-off 스칼라 결과'}</strong><small>{selected.analysis.hasDistribution ? '다운샘플된 실제 격자를 표시' : 'IED·IAD·IEAD 미생성'}</small></div></div><div className="analysis-selection-actions"><button className="button button--primary" type="button" data-action="analysis-forward" onClick={()=>onReference?.(selectedRef)} data-run-id={selected.runId}>이 Run으로 Agent에게 질문</button><button className="button button--secondary" type="button" data-action="open-decision" onClick={()=>onDecision?.(selectedRef)} data-run-id={selected.runId}>실험 기록</button></div></aside></div>
      </section>
      <section className="analysis-kpi-grid" aria-label={`${selected.runId} 핵심 실험 결과`}>{kpis.map(([label, value, unit]) => <Fragment key={label}><article><span>{label}</span><strong>{value}</strong><small>{unit}</small></article></Fragment>)}</section>
      <section className="panel analysis-detail-panel"><div className="analysis-detail-head"><div><span className="section-kicker">MEASURED OUTPUTS</span><h2>{selected.runId} 세부 결과</h2><p>스칼라는 전체 150개 Run, 쉬스 분포는 Bias-on 125개 Run에서 제공됩니다.</p></div><div className="analysis-head-actions"><button className="button button--secondary button--small" type="button" data-action="analysis-forward" onClick={()=>onReference?.(selectedRef)} data-run-id={selected.runId}>이 Run으로 Agent에게 질문</button><button className="button button--primary button--small" type="button" data-action="open-decision" onClick={()=>onDecision?.(selectedRef)} data-run-id={selected.runId}>코멘트·의사결정</button></div></div><div className="analysis-tabs" role="tablist" aria-label="실험 상세 그래프">{tabs.map(([id, label, hint]) => <Fragment key={id}><button type="button" role="tab" aria-selected={state.analysisTab === id} className={state.analysisTab === id ? 'is-active' : ''} data-action="analysis-tab" onClick={()=>update({analysisTab:id})} data-tab={id}><strong>{label}</strong><small>{hint}</small></button></Fragment>)}</div><div className="analysis-chart-content">{renderAnalysisChartContent(selected,state.analysisTab)}</div></section>
      <section className="analysis-provenance"><div><span className="section-kicker">DATA POLICY</span><h2>예측 없이 원본 출력을 요약합니다</h2><p>그래프의 점과 격자는 K-PLASMA 결과 파일에 실제로 기록된 값을 다운샘플링한 것입니다. 중간값 보간과 미실행 조건 예측은 포함하지 않습니다.</p></div><div><strong>{selected.sourceFiles.length}</strong><span>추적 가능 원본 파일</span></div><div><strong>{selected.analysis.strictConvergence ? 'PASS' : 'REVIEW'}</strong><span>strict residual 기준</span></div></section></>;
}
